-- This file contains SQL statements that will be executed after the build script.

EXECUTE [ADMINISTRACION].[PROC_INSERT_OR_UPDATE_CATALOG] 
   'GENERO'
  ,'Genéneros'
GO

EXECUTE [ADMINISTRACION].[PROC_INSERT_OR_UPDATE_CATALOG] 
 'GENERO_MASCULINO'
  ,'Masculino'
 ,'GENERO'
GO

EXECUTE [ADMINISTRACION].[PROC_INSERT_OR_UPDATE_CATALOG] 
 'GENERO_FEMENINO'
  ,'Femenino'
 ,'GENERO'
GO

EXECUTE [ADMINISTRACION].[PROC_INSERT_OR_UPDATE_CATALOG] 
 'DIA_SEMANA'
  ,'Día de la semana'
GO

EXECUTE [ADMINISTRACION].[PROC_INSERT_OR_UPDATE_CATALOG] 
 'DIA_SEMANA_LUNES'
  ,'Lunes'
 ,'DIA_SEMANA'
GO

EXECUTE [ADMINISTRACION].[PROC_INSERT_OR_UPDATE_CATALOG]  
 'DIA_SEMANA_MARTES'
  ,'Martes'
 ,'DIA_SEMANA'
GO

EXECUTE [ADMINISTRACION].[PROC_INSERT_OR_UPDATE_CATALOG]  
 'DIA_SEMANA_MIERCOLES'
  ,'Miércoles'
 ,'DIA_SEMANA'
GO

EXECUTE [ADMINISTRACION].[PROC_INSERT_OR_UPDATE_CATALOG]    
 'DIA_SEMANA_JUEVES'
  ,'Jueves'
 ,'DIA_SEMANA'
GO

EXECUTE [ADMINISTRACION].[PROC_INSERT_OR_UPDATE_CATALOG]    
 'DIA_SEMANA_VIERNES'
  ,'Viernes'
 ,'DIA_SEMANA'
GO

EXECUTE [ADMINISTRACION].[PROC_INSERT_OR_UPDATE_CATALOG] 
 'DIA_SEMANA_SABADO'
  ,'Sábado'
 ,'DIA_SEMANA'
GO

EXECUTE [ADMINISTRACION].[PROC_INSERT_OR_UPDATE_CATALOG] 
 'DIA_SEMANA_DOMINGO'
  ,'Domingo'
 ,'DIA_SEMANA'
GO


---------------

EXECUTE [ADMINISTRACION].[PROC_INSERT_OR_UPDATE_CATALOG] 
 'TIPOS_DOCU'
  ,'Día de la semana'
GO

EXECUTE [ADMINISTRACION].[PROC_INSERT_OR_UPDATE_CATALOG] 
 'DIA_SEMANA_DOMINGO'
  ,'Domingo'
 ,'DIA_SEMANA'
GO
