-- =============================================
-- Script: Crear tabla ENTRENADOR_GIMNASIO
-- Descripción: Tabla de relación entre Entrenadores y Gimnasios
-- Autor: Sistema
-- Fecha: 2025-10-28
-- =============================================

-- Crear tabla ENTRENADOR_GIMNASIO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[CORE].[ENTRENADOR_GIMNASIO]') AND type in (N'U'))
BEGIN
    CREATE TABLE [CORE].[ENTRENADOR_GIMNASIO](
        [EGY_ID] [INT] IDENTITY(1,1) NOT NULL,
        [EGY_GUID] [UNIQUEIDENTIFIER] NOT NULL,
        [EGY_FECHA_REGISTRO] [DATETIME] NOT NULL,
        [ENT_ID] [INT] NOT NULL,
        [GYM_ID] [INT] NOT NULL,
        [EGY_ESTADO] [BIT] NOT NULL,
        [EGY_FECHA_INICIO] [DATETIME] NULL,
        [EGY_FECHA_FIN] [DATETIME] NULL,
        [USR_ID_REGISTRADOR] [INT] NULL,
        CONSTRAINT [PK_ENTRENADOR_GIMNASIO] PRIMARY KEY CLUSTERED ([EGY_ID] ASC)
            WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
    ) ON [PRIMARY]

    -- Agregar restricción de GUID único
    ALTER TABLE [CORE].[ENTRENADOR_GIMNASIO] ADD CONSTRAINT [UQ_ENTRENADOR_GIMNASIO_GUID] UNIQUE([EGY_GUID])

    -- Agregar restricción de valor por defecto para GUID
    ALTER TABLE [CORE].[ENTRENADOR_GIMNASIO] ADD CONSTRAINT [DF_ENTRENADOR_GIMNASIO_GUID] DEFAULT (NEWID()) FOR [EGY_GUID]

    -- Agregar restricción de valor por defecto para fecha de registro
    ALTER TABLE [CORE].[ENTRENADOR_GIMNASIO] ADD CONSTRAINT [DF_ENTRENADOR_GIMNASIO_FECHA_REGISTRO] DEFAULT (GETDATE()) FOR [EGY_FECHA_REGISTRO]

    -- Agregar restricción de valor por defecto para estado
    ALTER TABLE [CORE].[ENTRENADOR_GIMNASIO] ADD CONSTRAINT [DF_ENTRENADOR_GIMNASIO_ESTADO] DEFAULT (1) FOR [EGY_ESTADO]

    -- Agregar foreign key al Entrenador
    ALTER TABLE [CORE].[ENTRENADOR_GIMNASIO] WITH CHECK ADD CONSTRAINT [FK_ENTRENADOR_GIMNASIO_ENTRENADOR] 
        FOREIGN KEY([ENT_ID]) REFERENCES [CORE].[ENTRENADORES] ([ENT_ID])
        ON DELETE CASCADE

    ALTER TABLE [CORE].[ENTRENADOR_GIMNASIO] CHECK CONSTRAINT [FK_ENTRENADOR_GIMNASIO_ENTRENADOR]

    -- Agregar foreign key al Gimnasio
    ALTER TABLE [CORE].[ENTRENADOR_GIMNASIO] WITH CHECK ADD CONSTRAINT [FK_ENTRENADOR_GIMNASIO_GIMNASIO] 
        FOREIGN KEY([GYM_ID]) REFERENCES [CORE].[GIMNASIO] ([GYM_ID])
        ON DELETE CASCADE

    ALTER TABLE [CORE].[ENTRENADOR_GIMNASIO] CHECK CONSTRAINT [FK_ENTRENADOR_GIMNASIO_GIMNASIO]

    -- Crear índice en ENT_ID
    CREATE NONCLUSTERED INDEX [IX_ENTRENADOR_GIMNASIO_ENT_ID] ON [CORE].[ENTRENADOR_GIMNASIO]
    (
        [ENT_ID] ASC
    ) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]

    -- Crear índice en GYM_ID
    CREATE NONCLUSTERED INDEX [IX_ENTRENADOR_GIMNASIO_GYM_ID] ON [CORE].[ENTRENADOR_GIMNASIO]
    (
        [GYM_ID] ASC
    ) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]

    -- Crear índice único compuesto para evitar duplicados (un entrenador activo no puede estar dos veces en el mismo gimnasio)
    CREATE UNIQUE NONCLUSTERED INDEX [UQ_ENTRENADOR_GIMNASIO_ACTIVO] ON [CORE].[ENTRENADOR_GIMNASIO]
    (
        [ENT_ID] ASC,
        [GYM_ID] ASC
    )
    WHERE [EGY_ESTADO] = 1
    WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]

    PRINT 'Tabla ENTRENADOR_GIMNASIO creada exitosamente'
END
ELSE
BEGIN
    PRINT 'La tabla ENTRENADOR_GIMNASIO ya existe'
END
GO

