-- Script para insertar datos en la tabla RUTA_BASE_ARCHIVO
-- Tabla: [Gym].[ADMINISTRACION].[RUTA_BASE_ARCHIVO]

USE [Gym]
GO

-- Insertar registros en RUTA_BASE_ARCHIVO
INSERT INTO [ADMINISTRACION].[RUTA_BASE_ARCHIVO]
    ([FBP_CODIGO], [FBP_BASE_URL], [FBP_RUTA_DIRECTORIO_ARCHIVO], [FBP_IMPLEMENTACION])
VALUES
    ('USER_IMAGE', 'http://127.0.0.1:10000/devstoreaccount1', '/Source/image', 'AzureStorage')
GO

INSERT INTO [ADMINISTRACION].[RUTA_BASE_ARCHIVO]
    ([FBP_CODIGO], [FBP_BASE_URL], [FBP_RUTA_DIRECTORIO_ARCHIVO], [FBP_IMPLEMENTACION])
VALUES
    ('GYM_BRANCH_IMAGE', 'http://127.0.0.1:10000/devstoreaccount1', '/gymbranch', 'AzureStorage')
GO

INSERT INTO [ADMINISTRACION].[RUTA_BASE_ARCHIVO]
    ([FBP_CODIGO], [FBP_BASE_URL], [FBP_RUTA_DIRECTORIO_ARCHIVO], [FBP_IMPLEMENTACION])
VALUES
    ('PROCESS_TRACKING_IMAGE', 'http://127.0.0.1:10000/devstoreaccount1', '/processtracking', 'AzureStorage')
GO

INSERT INTO [ADMINISTRACION].[RUTA_BASE_ARCHIVO]
    ([FBP_CODIGO], [FBP_BASE_URL], [FBP_RUTA_DIRECTORIO_ARCHIVO], [FBP_IMPLEMENTACION])
VALUES
    ('EQUIPMENT_IMAGE', 'http://127.0.0.1:10000/devstoreaccount1', '/equipment', 'AzureStorage')
GO


INSERT INTO [ADMINISTRACION].[RUTA_BASE_ARCHIVO]
    ([FBP_CODIGO], [FBP_BASE_URL], [FBP_RUTA_DIRECTORIO_ARCHIVO], [FBP_IMPLEMENTACION])
VALUES
    ('EXERCISE_IMAGE', 'http://127.0.0.1:10000/devstoreaccount1', '/exercise', 'AzureStorage')
GO
