-- This file contains SQL statements that will be executed after the build script.

EXECUTE [ADMINISTRACION].[PROC_INSERT_OR_UPDATE_CATALOG] 
   'GENERO'
  ,'Genéneros'
GO

EXECUTE [ADMINISTRACION].[PROC_INSERT_OR_UPDATE_CATALOG] 
 'GENERO_MASCULINO'
  ,'Masculino'
 ,'GENERO'
GO

EXECUTE [ADMINISTRACION].[PROC_INSERT_OR_UPDATE_CATALOG] 
 'GENERO_FEMENINO'
  ,'Femenino'
 ,'GENERO'
GO

EXECUTE [ADMINISTRACION].[PROC_INSERT_OR_UPDATE_CATALOG] 
 'DIA_SEMANA'
  ,'Día de la semana'
GO

EXECUTE [ADMINISTRACION].[PROC_INSERT_OR_UPDATE_CATALOG] 
 'DIA_SEMANA_LUNES'
  ,'Lunes'
 ,'DIA_SEMANA'
GO

EXECUTE [ADMINISTRACION].[PROC_INSERT_OR_UPDATE_CATALOG]  
 'DIA_SEMANA_MARTES'
  ,'Martes'
 ,'DIA_SEMANA'
GO

EXECUTE [ADMINISTRACION].[PROC_INSERT_OR_UPDATE_CATALOG]  
 'DIA_SEMANA_MIERCOLES'
  ,'Miércoles'
 ,'DIA_SEMANA'
GO

EXECUTE [ADMINISTRACION].[PROC_INSERT_OR_UPDATE_CATALOG]    
 'DIA_SEMANA_JUEVES'
  ,'Jueves'
 ,'DIA_SEMANA'
GO

EXECUTE [ADMINISTRACION].[PROC_INSERT_OR_UPDATE_CATALOG]    
 'DIA_SEMANA_VIERNES'
  ,'Viernes'
 ,'DIA_SEMANA'
GO

EXECUTE [ADMINISTRACION].[PROC_INSERT_OR_UPDATE_CATALOG] 
 'DIA_SEMANA_SABADO'
  ,'Sábado'
 ,'DIA_SEMANA'
GO

EXECUTE [ADMINISTRACION].[PROC_INSERT_OR_UPDATE_CATALOG] 
 'DIA_SEMANA_DOMINGO'
  ,'Domingo'
 ,'DIA_SEMANA'
GO


---------------

EXECUTE [ADMINISTRACION].[PROC_INSERT_OR_UPDATE_CATALOG] 
 'TIPOS_DOCU'
  ,'Día de la semana'
GO

EXECUTE [ADMINISTRACION].[PROC_INSERT_OR_UPDATE_CATALOG] 
 'DIA_SEMANA_DOMINGO'
  ,'Domingo'
 ,'DIA_SEMANA'
GO


---------------

EXECUTE [ADMINISTRACION].[PROC_INSERT_OR_UPDATE_CATALOG] 
 'TIPOS_EQUIPO_GIMNASIO'
  ,'Tipos de Equipo Gimnasio'
GO

EXECUTE [ADMINISTRACION].[PROC_INSERT_OR_UPDATE_CATALOG] 
 'TIPOS_EQUIPO_MAQUINA_PESO_FIJO'
  ,'Máquina Peso Fijo'
 ,'TIPOS_EQUIPO_GIMNASIO'
GO

EXECUTE [ADMINISTRACION].[PROC_INSERT_OR_UPDATE_CATALOG] 
 'TIPOS_EQUIPO_MAQUINA_PESO_LIBRE'
  ,'Máquina Peso Libre'
 ,'TIPOS_EQUIPO_GIMNASIO'
GO

EXECUTE [ADMINISTRACION].[PROC_INSERT_OR_UPDATE_CATALOG] 
 'TIPOS_EQUIPO_MULTIFUNCION'
  ,'Multifunción'
 ,'TIPOS_EQUIPO_GIMNASIO'
GO

EXECUTE [ADMINISTRACION].[PROC_INSERT_OR_UPDATE_CATALOG] 
 'TIPOS_EQUIPO_ACCESORIO'
  ,'Accesorio'
 ,'TIPOS_EQUIPO_GIMNASIO'
GO

EXECUTE [ADMINISTRACION].[PROC_INSERT_OR_UPDATE_CATALOG] 
 'NOMBRES_MUSCULOS'
  ,'Nombre de Músculos'
GO

EXECUTE [ADMINISTRACION].[PROC_INSERT_OR_UPDATE_CATALOG] 
 'MUSCULO_PECTORAL'
  ,'Pectoral'
 ,'NOMBRES_MUSCULOS'
GO

EXECUTE [ADMINISTRACION].[PROC_INSERT_OR_UPDATE_CATALOG] 
 'MUSCULO_DELTOIDES'
  ,'Deltoides'
 ,'NOMBRES_MUSCULOS'
GO

EXECUTE [ADMINISTRACION].[PROC_INSERT_OR_UPDATE_CATALOG] 
 'MUSCULO_BICEPS'
  ,'Bíceps'
 ,'NOMBRES_MUSCULOS'
GO

EXECUTE [ADMINISTRACION].[PROC_INSERT_OR_UPDATE_CATALOG] 
 'MUSCULO_TRICEPS'
  ,'Tríceps'
 ,'NOMBRES_MUSCULOS'
GO

EXECUTE [ADMINISTRACION].[PROC_INSERT_OR_UPDATE_CATALOG] 
 'MUSCULO_CUADRICEPS'
  ,'Cuádriceps'
 ,'NOMBRES_MUSCULOS'
GO

EXECUTE [ADMINISTRACION].[PROC_INSERT_OR_UPDATE_CATALOG] 
 'MUSCULO_ISQUIOTIBIALES'
  ,'Isquiotibiales'
 ,'NOMBRES_MUSCULOS'
GO

EXECUTE [ADMINISTRACION].[PROC_INSERT_OR_UPDATE_CATALOG] 
 'MUSCULO_GLUTEOS'
  ,'Glúteos'
 ,'NOMBRES_MUSCULOS'
GO

EXECUTE [ADMINISTRACION].[PROC_INSERT_OR_UPDATE_CATALOG] 
 'MUSCULO_ABDOMINALES'
  ,'Abdominales'
 ,'NOMBRES_MUSCULOS'
GO

EXECUTE [ADMINISTRACION].[PROC_INSERT_OR_UPDATE_CATALOG] 
 'MUSCULO_DORSALES'
  ,'Dorsales'
 ,'NOMBRES_MUSCULOS'
GO

EXECUTE [ADMINISTRACION].[PROC_INSERT_OR_UPDATE_CATALOG] 
 'MUSCULO_TRAPECIO'
  ,'Trapecio'
 ,'NOMBRES_MUSCULOS'
GO

EXECUTE [ADMINISTRACION].[PROC_INSERT_OR_UPDATE_CATALOG] 
 'MUSCULO_SERRATO_ANTERIOR'
  ,'Serrato Anterior'
 ,'NOMBRES_MUSCULOS'
GO

EXECUTE [ADMINISTRACION].[PROC_INSERT_OR_UPDATE_CATALOG] 
 'MUSCULO_ANTEBRAZO'
  ,'Antebrazo'
 ,'NOMBRES_MUSCULOS'
GO

EXECUTE [ADMINISTRACION].[PROC_INSERT_OR_UPDATE_CATALOG] 
 'MUSCULO_GEMELOS'
  ,'Gemelos'
 ,'NOMBRES_MUSCULOS'
GO

EXECUTE [ADMINISTRACION].[PROC_INSERT_OR_UPDATE_CATALOG] 
 'MUSCULO_ADUCTORES'
  ,'Aductores'
 ,'NOMBRES_MUSCULOS'
GO

EXECUTE [ADMINISTRACION].[PROC_INSERT_OR_UPDATE_CATALOG] 
 'MUSCULO_ABDUCTORES'
  ,'Abductores'
 ,'NOMBRES_MUSCULOS'
GO

EXECUTE [ADMINISTRACION].[PROC_INSERT_OR_UPDATE_CATALOG] 
 'MUSCULO_CORE'
  ,'Core'
 ,'NOMBRES_MUSCULOS'
GO

EXECUTE [ADMINISTRACION].[PROC_INSERT_OR_UPDATE_CATALOG] 
 'MUSCULO_LUMBARES'
  ,'Lumbares'
 ,'NOMBRES_MUSCULOS'
GO

EXECUTE [ADMINISTRACION].[PROC_INSERT_OR_UPDATE_CATALOG] 
 'MUSCULO_OBLICUOS'
  ,'Oblicuos'
 ,'NOMBRES_MUSCULOS'
GO

EXECUTE [ADMINISTRACION].[PROC_INSERT_OR_UPDATE_CATALOG] 
 'MUSCULO_MANGUITO_ROTADOR'
  ,'Manguito Rotador'
 ,'NOMBRES_MUSCULOS'
GO

EXECUTE [ADMINISTRACION].[PROC_INSERT_OR_UPDATE_CATALOG] 
 'MUSCULO_ESPALDA_MEDIA'
  ,'Espalda Media'
 ,'NOMBRES_MUSCULOS'
GO

EXECUTE [ADMINISTRACION].[PROC_INSERT_OR_UPDATE_CATALOG] 
 'MUSCULO_ESPALDA_BAJA'
  ,'Espalda Baja'
 ,'NOMBRES_MUSCULOS'
GO

EXECUTE [ADMINISTRACION].[PROC_INSERT_OR_UPDATE_CATALOG] 
 'MUSCULO_PANTORRILLA'
  ,'Pantorrilla'
 ,'NOMBRES_MUSCULOS'
GO

EXECUTE [ADMINISTRACION].[PROC_INSERT_OR_UPDATE_CATALOG] 
 'MUSCULO_CUADRICEPS_FEMORAL'
  ,'Cuádriceps Femoral'
 ,'NOMBRES_MUSCULOS'
GO

EXECUTE [ADMINISTRACION].[PROC_INSERT_OR_UPDATE_CATALOG] 
 'MUSCULO_FLEXORES_CADERA'
  ,'Flexores de Cadera'
 ,'NOMBRES_MUSCULOS'
GO

EXECUTE [ADMINISTRACION].[PROC_INSERT_OR_UPDATE_CATALOG] 
 'MUSCULO_ROMBOIDES'
  ,'Romboides'
 ,'NOMBRES_MUSCULOS'
GO

EXECUTE [ADMINISTRACION].[PROC_INSERT_OR_UPDATE_CATALOG] 
 'MUSCULO_REDONDO_MAYOR'
  ,'Redondo Mayor'
 ,'NOMBRES_MUSCULOS'
GO

EXECUTE [ADMINISTRACION].[PROC_INSERT_OR_UPDATE_CATALOG] 
 'MUSCULO_REDONDO_MENOR'
  ,'Redondo Menor'
 ,'NOMBRES_MUSCULOS'
GO

EXECUTE [ADMINISTRACION].[PROC_INSERT_OR_UPDATE_CATALOG] 
 'MUSCULO_SUPRAESPINOSO'
  ,'Supraespinoso'
 ,'NOMBRES_MUSCULOS'
GO

EXECUTE [ADMINISTRACION].[PROC_INSERT_OR_UPDATE_CATALOG] 
 'MUSCULO_INFRAESPINOSO'
  ,'Infraespinoso'
 ,'NOMBRES_MUSCULOS'
GO

EXECUTE [ADMINISTRACION].[PROC_INSERT_OR_UPDATE_CATALOG] 
 'MUSCULO_SUBESCAPULAR'
  ,'Subescapular'
 ,'NOMBRES_MUSCULOS'
GO