-- =================================================================
-- Migración: medidas escalables en SEGUIMIENTO_PROCESOS
-- Crea PARAMETROS_FISICOS + SEGUIMIENTO_PROCESOS_MEDIDAS,
-- migra datos desde columnas fijas y elimina columnas de medida.
-- =================================================================

USE [Gym];
GO

SET ANSI_NULLS ON;
GO

SET QUOTED_IDENTIFIER ON;
GO

BEGIN TRANSACTION;
GO

BEGIN TRY
    PRINT 'Iniciando migración de medidas ProcessTracking...';

    -- 1. PARAMETROS_FISICOS
    IF NOT EXISTS (SELECT 1 FROM sys.tables t JOIN sys.schemas s ON t.schema_id = s.schema_id WHERE s.name = 'CORE' AND t.name = 'PARAMETROS_FISICOS')
    BEGIN
        CREATE TABLE [CORE].[PARAMETROS_FISICOS] (
            [PAF_ID]     INT            IDENTITY (1, 1) NOT NULL,
            [PAF_CODIGO] VARCHAR (64)   NOT NULL,
            [PAF_NOMBRE] NVARCHAR (128) NOT NULL,
            [PAF_ESTADO] BIT            NOT NULL CONSTRAINT [DF_PARAMETROS_FISICOS_ESTADO] DEFAULT (1),
            CONSTRAINT [PK_PARAMETROS_FISICOS] PRIMARY KEY CLUSTERED ([PAF_ID] ASC)
        );

        CREATE UNIQUE NONCLUSTERED INDEX [UQ_PARAMETROS_FISICOS_CODIGO]
            ON [CORE].[PARAMETROS_FISICOS]([PAF_CODIGO] ASC);

        PRINT 'Tabla CORE.PARAMETROS_FISICOS creada.';
    END

    -- 2. Normalizar códigos en inglés a español (si la migración se ejecutó con versión anterior)
    UPDATE paf SET [PAF_CODIGO] = 'PESO'
    FROM [CORE].[PARAMETROS_FISICOS] paf WHERE paf.[PAF_CODIGO] = 'WEIGHT';
    UPDATE paf SET [PAF_CODIGO] = 'ALTURA'
    FROM [CORE].[PARAMETROS_FISICOS] paf WHERE paf.[PAF_CODIGO] = 'HEIGHT';
    UPDATE paf SET [PAF_CODIGO] = 'GRASA_PORCENTAJE'
    FROM [CORE].[PARAMETROS_FISICOS] paf WHERE paf.[PAF_CODIGO] = 'BODY_FAT_PERCENTAGE';
    UPDATE paf SET [PAF_CODIGO] = 'MUSCULO_PORCENTAJE'
    FROM [CORE].[PARAMETROS_FISICOS] paf WHERE paf.[PAF_CODIGO] = 'MUSCLE_MASS_PERCENTAGE';
    UPDATE paf SET [PAF_CODIGO] = 'MEDIDA_PECHO'
    FROM [CORE].[PARAMETROS_FISICOS] paf WHERE paf.[PAF_CODIGO] = 'CHEST_MEASUREMENT';
    UPDATE paf SET [PAF_CODIGO] = 'MEDIDA_CINTURA'
    FROM [CORE].[PARAMETROS_FISICOS] paf WHERE paf.[PAF_CODIGO] = 'WAIST_MEASUREMENT';
    UPDATE paf SET [PAF_CODIGO] = 'MEDIDA_CADERA'
    FROM [CORE].[PARAMETROS_FISICOS] paf WHERE paf.[PAF_CODIGO] = 'HIP_MEASUREMENT';
    UPDATE paf SET [PAF_CODIGO] = 'MEDIDA_BRAZO_DER'
    FROM [CORE].[PARAMETROS_FISICOS] paf WHERE paf.[PAF_CODIGO] = 'ARM_RIGHT_MEASUREMENT';
    UPDATE paf SET [PAF_CODIGO] = 'MEDIDA_MUSLO_DER'
    FROM [CORE].[PARAMETROS_FISICOS] paf WHERE paf.[PAF_CODIGO] = 'THIGH_RIGHT_MEASUREMENT';

    -- 3. Seed catálogo (códigos en español)
    MERGE [CORE].[PARAMETROS_FISICOS] AS target
    USING (VALUES
        ('PESO',                N'Peso (kg)',              1),
        ('ALTURA',              N'Altura (cm)',            1),
        ('GRASA_PORCENTAJE',    N'% Grasa corporal',       1),
        ('MUSCULO_PORCENTAJE',  N'% Masa muscular',        1),
        ('MEDIDA_PECHO',         N'Medida pecho (cm)',      1),
        ('MEDIDA_CINTURA',       N'Medida cintura (cm)',    1),
        ('MEDIDA_CADERA',        N'Medida cadera (cm)',     1),
        ('MEDIDA_BRAZO_DER',     N'Medida brazo der. (cm)', 1),
        ('MEDIDA_MUSLO_DER',     N'Medida muslo der. (cm)', 1),
        ('IMC',                  N'Índice de masa corporal', 1)
    ) AS source ([PAF_CODIGO], [PAF_NOMBRE], [PAF_ESTADO])
    ON target.[PAF_CODIGO] = source.[PAF_CODIGO]
    WHEN NOT MATCHED BY TARGET THEN
        INSERT ([PAF_CODIGO], [PAF_NOMBRE], [PAF_ESTADO])
        VALUES (source.[PAF_CODIGO], source.[PAF_NOMBRE], source.[PAF_ESTADO]);

    PRINT 'Catálogo PARAMETROS_FISICOS cargado.';

    -- 4. SEGUIMIENTO_PROCESOS_MEDIDAS
    IF NOT EXISTS (SELECT 1 FROM sys.tables t JOIN sys.schemas s ON t.schema_id = s.schema_id WHERE s.name = 'CORE' AND t.name = 'SEGUIMIENTO_PROCESOS_MEDIDAS')
    BEGIN
        CREATE TABLE [CORE].[SEGUIMIENTO_PROCESOS_MEDIDAS] (
            [SPM_ID]    INT            IDENTITY (1, 1) NOT NULL,
            [SPR_ID]    INT            NOT NULL,
            [PAF_ID]    INT            NOT NULL,
            [SPM_VALOR] DECIMAL (5, 2) NOT NULL,
            CONSTRAINT [PK_SEGUIMIENTO_PROCESOS_MEDIDAS] PRIMARY KEY CLUSTERED ([SPM_ID] ASC),
            CONSTRAINT [FK_SEGUIMIENTO_PROCESOS_MEDIDAS_PARAMETROS_FISICOS] FOREIGN KEY ([PAF_ID]) REFERENCES [CORE].[PARAMETROS_FISICOS] ([PAF_ID]),
            CONSTRAINT [FK_SEGUIMIENTO_PROCESOS_MEDIDAS_SEGUIMIENTO_PROCESOS] FOREIGN KEY ([SPR_ID]) REFERENCES [CORE].[SEGUIMIENTO_PROCESOS] ([SPR_ID]) ON DELETE CASCADE
        );

        CREATE UNIQUE NONCLUSTERED INDEX [UQ_SEGUIMIENTO_PROCESOS_MEDIDAS_SPR_PAF]
            ON [CORE].[SEGUIMIENTO_PROCESOS_MEDIDAS]([SPR_ID] ASC, [PAF_ID] ASC);

        PRINT 'Tabla CORE.SEGUIMIENTO_PROCESOS_MEDIDAS creada.';
    END

    -- 5. Migrar datos (solo si existen columnas origen)
    IF COL_LENGTH('CORE.SEGUIMIENTO_PROCESOS', 'SPR_PESO') IS NOT NULL
    BEGIN
        INSERT INTO [CORE].[SEGUIMIENTO_PROCESOS_MEDIDAS] ([SPR_ID], [PAF_ID], [SPM_VALOR])
        SELECT spr.[SPR_ID], paf.[PAF_ID], spr.[SPR_PESO]
        FROM [CORE].[SEGUIMIENTO_PROCESOS] spr
        INNER JOIN [CORE].[PARAMETROS_FISICOS] paf ON paf.[PAF_CODIGO] = 'PESO'
        WHERE NOT EXISTS (
            SELECT 1 FROM [CORE].[SEGUIMIENTO_PROCESOS_MEDIDAS] spm
            WHERE spm.[SPR_ID] = spr.[SPR_ID] AND spm.[PAF_ID] = paf.[PAF_ID]
        );

        INSERT INTO [CORE].[SEGUIMIENTO_PROCESOS_MEDIDAS] ([SPR_ID], [PAF_ID], [SPM_VALOR])
        SELECT spr.[SPR_ID], paf.[PAF_ID], spr.[SPR_ALTURA]
        FROM [CORE].[SEGUIMIENTO_PROCESOS] spr
        INNER JOIN [CORE].[PARAMETROS_FISICOS] paf ON paf.[PAF_CODIGO] = 'ALTURA'
        WHERE NOT EXISTS (
            SELECT 1 FROM [CORE].[SEGUIMIENTO_PROCESOS_MEDIDAS] spm
            WHERE spm.[SPR_ID] = spr.[SPR_ID] AND spm.[PAF_ID] = paf.[PAF_ID]
        );

        INSERT INTO [CORE].[SEGUIMIENTO_PROCESOS_MEDIDAS] ([SPR_ID], [PAF_ID], [SPM_VALOR])
        SELECT spr.[SPR_ID], paf.[PAF_ID], spr.[SPR_GRASA_PORCENTAJE]
        FROM [CORE].[SEGUIMIENTO_PROCESOS] spr
        INNER JOIN [CORE].[PARAMETROS_FISICOS] paf ON paf.[PAF_CODIGO] = 'GRASA_PORCENTAJE'
        WHERE spr.[SPR_GRASA_PORCENTAJE] IS NOT NULL
          AND NOT EXISTS (
            SELECT 1 FROM [CORE].[SEGUIMIENTO_PROCESOS_MEDIDAS] spm
            WHERE spm.[SPR_ID] = spr.[SPR_ID] AND spm.[PAF_ID] = paf.[PAF_ID]
        );

        INSERT INTO [CORE].[SEGUIMIENTO_PROCESOS_MEDIDAS] ([SPR_ID], [PAF_ID], [SPM_VALOR])
        SELECT spr.[SPR_ID], paf.[PAF_ID], spr.[SPR_MUSCULO_PORCENTAJE]
        FROM [CORE].[SEGUIMIENTO_PROCESOS] spr
        INNER JOIN [CORE].[PARAMETROS_FISICOS] paf ON paf.[PAF_CODIGO] = 'MUSCULO_PORCENTAJE'
        WHERE spr.[SPR_MUSCULO_PORCENTAJE] IS NOT NULL
          AND NOT EXISTS (
            SELECT 1 FROM [CORE].[SEGUIMIENTO_PROCESOS_MEDIDAS] spm
            WHERE spm.[SPR_ID] = spr.[SPR_ID] AND spm.[PAF_ID] = paf.[PAF_ID]
        );

        INSERT INTO [CORE].[SEGUIMIENTO_PROCESOS_MEDIDAS] ([SPR_ID], [PAF_ID], [SPM_VALOR])
        SELECT spr.[SPR_ID], paf.[PAF_ID], spr.[SPR_MEDIDA_PECHO]
        FROM [CORE].[SEGUIMIENTO_PROCESOS] spr
        INNER JOIN [CORE].[PARAMETROS_FISICOS] paf ON paf.[PAF_CODIGO] = 'MEDIDA_PECHO'
        WHERE spr.[SPR_MEDIDA_PECHO] IS NOT NULL
          AND NOT EXISTS (
            SELECT 1 FROM [CORE].[SEGUIMIENTO_PROCESOS_MEDIDAS] spm
            WHERE spm.[SPR_ID] = spr.[SPR_ID] AND spm.[PAF_ID] = paf.[PAF_ID]
        );

        INSERT INTO [CORE].[SEGUIMIENTO_PROCESOS_MEDIDAS] ([SPR_ID], [PAF_ID], [SPM_VALOR])
        SELECT spr.[SPR_ID], paf.[PAF_ID], spr.[SPR_MEDIDA_CINTURA]
        FROM [CORE].[SEGUIMIENTO_PROCESOS] spr
        INNER JOIN [CORE].[PARAMETROS_FISICOS] paf ON paf.[PAF_CODIGO] = 'MEDIDA_CINTURA'
        WHERE spr.[SPR_MEDIDA_CINTURA] IS NOT NULL
          AND NOT EXISTS (
            SELECT 1 FROM [CORE].[SEGUIMIENTO_PROCESOS_MEDIDAS] spm
            WHERE spm.[SPR_ID] = spr.[SPR_ID] AND spm.[PAF_ID] = paf.[PAF_ID]
        );

        INSERT INTO [CORE].[SEGUIMIENTO_PROCESOS_MEDIDAS] ([SPR_ID], [PAF_ID], [SPM_VALOR])
        SELECT spr.[SPR_ID], paf.[PAF_ID], spr.[SPR_MEDIDA_CADERA]
        FROM [CORE].[SEGUIMIENTO_PROCESOS] spr
        INNER JOIN [CORE].[PARAMETROS_FISICOS] paf ON paf.[PAF_CODIGO] = 'MEDIDA_CADERA'
        WHERE spr.[SPR_MEDIDA_CADERA] IS NOT NULL
          AND NOT EXISTS (
            SELECT 1 FROM [CORE].[SEGUIMIENTO_PROCESOS_MEDIDAS] spm
            WHERE spm.[SPR_ID] = spr.[SPR_ID] AND spm.[PAF_ID] = paf.[PAF_ID]
        );

        INSERT INTO [CORE].[SEGUIMIENTO_PROCESOS_MEDIDAS] ([SPR_ID], [PAF_ID], [SPM_VALOR])
        SELECT spr.[SPR_ID], paf.[PAF_ID], spr.[SPR_MEDIDA_BRAZO_DER]
        FROM [CORE].[SEGUIMIENTO_PROCESOS] spr
        INNER JOIN [CORE].[PARAMETROS_FISICOS] paf ON paf.[PAF_CODIGO] = 'MEDIDA_BRAZO_DER'
        WHERE spr.[SPR_MEDIDA_BRAZO_DER] IS NOT NULL
          AND NOT EXISTS (
            SELECT 1 FROM [CORE].[SEGUIMIENTO_PROCESOS_MEDIDAS] spm
            WHERE spm.[SPR_ID] = spr.[SPR_ID] AND spm.[PAF_ID] = paf.[PAF_ID]
        );

        INSERT INTO [CORE].[SEGUIMIENTO_PROCESOS_MEDIDAS] ([SPR_ID], [PAF_ID], [SPM_VALOR])
        SELECT spr.[SPR_ID], paf.[PAF_ID], spr.[SPR_MEDIDA_MUSLO_DER]
        FROM [CORE].[SEGUIMIENTO_PROCESOS] spr
        INNER JOIN [CORE].[PARAMETROS_FISICOS] paf ON paf.[PAF_CODIGO] = 'MEDIDA_MUSLO_DER'
        WHERE spr.[SPR_MEDIDA_MUSLO_DER] IS NOT NULL
          AND NOT EXISTS (
            SELECT 1 FROM [CORE].[SEGUIMIENTO_PROCESOS_MEDIDAS] spm
            WHERE spm.[SPR_ID] = spr.[SPR_ID] AND spm.[PAF_ID] = paf.[PAF_ID]
        );

        PRINT 'Datos migrados a SEGUIMIENTO_PROCESOS_MEDIDAS.';
    END
    ELSE
        PRINT 'Columnas de medida ya eliminadas; se omite migración de datos.';

    -- 6. Eliminar columnas de medida
    IF COL_LENGTH('CORE.SEGUIMIENTO_PROCESOS', 'SPR_PESO') IS NOT NULL
        ALTER TABLE [CORE].[SEGUIMIENTO_PROCESOS] DROP COLUMN [SPR_PESO];
    IF COL_LENGTH('CORE.SEGUIMIENTO_PROCESOS', 'SPR_ALTURA') IS NOT NULL
        ALTER TABLE [CORE].[SEGUIMIENTO_PROCESOS] DROP COLUMN [SPR_ALTURA];
    IF COL_LENGTH('CORE.SEGUIMIENTO_PROCESOS', 'SPR_GRASA_PORCENTAJE') IS NOT NULL
        ALTER TABLE [CORE].[SEGUIMIENTO_PROCESOS] DROP COLUMN [SPR_GRASA_PORCENTAJE];
    IF COL_LENGTH('CORE.SEGUIMIENTO_PROCESOS', 'SPR_MUSCULO_PORCENTAJE') IS NOT NULL
        ALTER TABLE [CORE].[SEGUIMIENTO_PROCESOS] DROP COLUMN [SPR_MUSCULO_PORCENTAJE];
    IF COL_LENGTH('CORE.SEGUIMIENTO_PROCESOS', 'SPR_MEDIDA_PECHO') IS NOT NULL
        ALTER TABLE [CORE].[SEGUIMIENTO_PROCESOS] DROP COLUMN [SPR_MEDIDA_PECHO];
    IF COL_LENGTH('CORE.SEGUIMIENTO_PROCESOS', 'SPR_MEDIDA_CINTURA') IS NOT NULL
        ALTER TABLE [CORE].[SEGUIMIENTO_PROCESOS] DROP COLUMN [SPR_MEDIDA_CINTURA];
    IF COL_LENGTH('CORE.SEGUIMIENTO_PROCESOS', 'SPR_MEDIDA_CADERA') IS NOT NULL
        ALTER TABLE [CORE].[SEGUIMIENTO_PROCESOS] DROP COLUMN [SPR_MEDIDA_CADERA];
    IF COL_LENGTH('CORE.SEGUIMIENTO_PROCESOS', 'SPR_MEDIDA_BRAZO_DER') IS NOT NULL
        ALTER TABLE [CORE].[SEGUIMIENTO_PROCESOS] DROP COLUMN [SPR_MEDIDA_BRAZO_DER];
    IF COL_LENGTH('CORE.SEGUIMIENTO_PROCESOS', 'SPR_MEDIDA_MUSLO_DER') IS NOT NULL
        ALTER TABLE [CORE].[SEGUIMIENTO_PROCESOS] DROP COLUMN [SPR_MEDIDA_MUSLO_DER];

    PRINT 'Columnas de medida eliminadas de SEGUIMIENTO_PROCESOS.';

    COMMIT TRANSACTION;
    PRINT 'Migración completada correctamente.';
END TRY
BEGIN CATCH
    IF @@TRANCOUNT > 0
        ROLLBACK TRANSACTION;

    DECLARE @ErrorMessage NVARCHAR(4000) = ERROR_MESSAGE();
    DECLARE @ErrorSeverity INT = ERROR_SEVERITY();
    DECLARE @ErrorState INT = ERROR_STATE();
    RAISERROR (@ErrorMessage, @ErrorSeverity, @ErrorState);
END CATCH;
GO
