-- =================================================================
-- Script de creación de tabla PLAN_SUSCRIPCION
-- Define los planes de pago/suscripción que ofrece un gimnasio
-- =================================================================

-- Crear tabla de planes de suscripción
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[CORE].[PLAN_SUSCRIPCION]') AND type in (N'U'))
BEGIN
    CREATE TABLE [CORE].[PLAN_SUSCRIPCION] (
        [PLS_ID] INT IDENTITY(1,1) NOT NULL,
        [PLS_GUID] UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID(),
        [GYM_ID] INT NOT NULL,
        [PLS_FECHA_REGISTRO] DATETIME NOT NULL DEFAULT GETDATE(),
        [PLS_NOMBRE] NVARCHAR(200) NOT NULL,
        [PLS_CODIGO] NVARCHAR(50) NULL,
        [PLS_DESCRIPCION] NVARCHAR(1000) NULL,
        [PLS_PRECIO] DECIMAL(18,2) NOT NULL,
        [ITC_MONEDA] INT NULL,
        [ITC_PERIODO_FACTURACION] INT NULL,
        [PLS_DURACION_DIAS] INT NOT NULL,
        [PLS_DIAS_PRUEBA_GRATIS] INT NULL,
        [PLS_PRECIO_INSCRIPCION] DECIMAL(18,2) NULL,
        [PLS_DESCUENTO_PORCENTAJE] DECIMAL(5,2) NULL,
        [PLS_LIMITE_ACCESOS_MES] INT NULL,
        [PLS_CLASES_GRUPALES_MES] INT NULL,
        [PLS_SESIONES_ENTRENADOR] INT NULL,
        [PLS_ACCESO_TODAS_SUCURSALES] BIT NOT NULL DEFAULT 0,
        [PLS_PERMITE_CONGELAR] BIT NOT NULL DEFAULT 1,
        [PLS_DIAS_MAX_CONGELAMIENTO] INT NULL,
        [PLS_PERMITE_INVITADOS] BIT NOT NULL DEFAULT 0,
        [PLS_NUM_INVITADOS_MES] INT NULL,
        [PLS_INCLUYE_SPA] BIT NOT NULL DEFAULT 0,
        [PLS_INCLUYE_CASILLERO] BIT NOT NULL DEFAULT 0,
        [PLS_INCLUYE_ESTACIONAMIENTO] BIT NOT NULL DEFAULT 0,
        [PLS_INCLUYE_NUTRICION] BIT NOT NULL DEFAULT 0,
        [PLS_PRIORIDAD_RESERVAS] INT NULL,
        [PLS_RENOVACION_AUTOMATICA] BIT NOT NULL DEFAULT 1,
        [PLS_REQUIERE_CONTRATO] BIT NOT NULL DEFAULT 0,
        [PLS_MESES_MIN_COMPROMISO] INT NULL,
        [PLS_PENALIZACION_CANCELACION] DECIMAL(18,2) NULL,
        [PLS_ORDEN] INT NULL,
        [PLS_ES_DESTACADO] BIT NOT NULL DEFAULT 0,
        [PLS_ESTADO] BIT NOT NULL DEFAULT 1,
        [PLS_FECHA_INICIO_VIGENCIA] DATETIME NULL,
        [PLS_FECHA_FIN_VIGENCIA] DATETIME NULL,
        [PLS_OBSERVACIONES] NVARCHAR(500) NULL,
        [USR_ID_REGISTRADOR] INT NULL,
        
        CONSTRAINT [PK_PLAN_SUSCRIPCION] PRIMARY KEY CLUSTERED ([PLS_ID] ASC),
        CONSTRAINT [FK_PLAN_SUSCRIPCION_GIMNASIO] FOREIGN KEY ([GYM_ID]) 
            REFERENCES [CORE].[GIMNASIO]([GYM_ID])
    );
    
    PRINT 'Tabla CORE.PLAN_SUSCRIPCION creada exitosamente.';
END
ELSE
BEGIN
    PRINT 'La tabla CORE.PLAN_SUSCRIPCION ya existe.';
END
GO

-- Crear índice único para el código del plan por gimnasio
IF NOT EXISTS (SELECT * FROM sys.indexes WHERE name = 'IX_PLAN_SUSCRIPCION_CODIGO_GYM' AND object_id = OBJECT_ID('CORE.PLAN_SUSCRIPCION'))
BEGIN
    CREATE UNIQUE NONCLUSTERED INDEX [IX_PLAN_SUSCRIPCION_CODIGO_GYM] 
    ON [CORE].[PLAN_SUSCRIPCION] ([GYM_ID], [PLS_CODIGO]) 
    WHERE [PLS_CODIGO] IS NOT NULL;
    PRINT 'Índice IX_PLAN_SUSCRIPCION_CODIGO_GYM creado.';
END
GO

-- Crear índice para el GUID
IF NOT EXISTS (SELECT * FROM sys.indexes WHERE name = 'IX_PLAN_SUSCRIPCION_GUID' AND object_id = OBJECT_ID('CORE.PLAN_SUSCRIPCION'))
BEGIN
    CREATE UNIQUE NONCLUSTERED INDEX [IX_PLAN_SUSCRIPCION_GUID] 
    ON [CORE].[PLAN_SUSCRIPCION] ([PLS_GUID]);
    PRINT 'Índice IX_PLAN_SUSCRIPCION_GUID creado.';
END
GO

-- Crear índice para gimnasio y estado
IF NOT EXISTS (SELECT * FROM sys.indexes WHERE name = 'IX_PLAN_SUSCRIPCION_GYM_ESTADO' AND object_id = OBJECT_ID('CORE.PLAN_SUSCRIPCION'))
BEGIN
    CREATE NONCLUSTERED INDEX [IX_PLAN_SUSCRIPCION_GYM_ESTADO] 
    ON [CORE].[PLAN_SUSCRIPCION] ([GYM_ID], [PLS_ESTADO], [PLS_ORDEN]);
    PRINT 'Índice IX_PLAN_SUSCRIPCION_GYM_ESTADO creado.';
END
GO

-- Crear índice para planes destacados
IF NOT EXISTS (SELECT * FROM sys.indexes WHERE name = 'IX_PLAN_SUSCRIPCION_DESTACADO' AND object_id = OBJECT_ID('CORE.PLAN_SUSCRIPCION'))
BEGIN
    CREATE NONCLUSTERED INDEX [IX_PLAN_SUSCRIPCION_DESTACADO] 
    ON [CORE].[PLAN_SUSCRIPCION] ([PLS_ES_DESTACADO], [PLS_ESTADO]) 
    INCLUDE ([GYM_ID], [PLS_NOMBRE], [PLS_PRECIO]);
    PRINT 'Índice IX_PLAN_SUSCRIPCION_DESTACADO creado.';
END
GO

-- Crear índice para fechas de vigencia
IF NOT EXISTS (SELECT * FROM sys.indexes WHERE name = 'IX_PLAN_SUSCRIPCION_VIGENCIA' AND object_id = OBJECT_ID('CORE.PLAN_SUSCRIPCION'))
BEGIN
    CREATE NONCLUSTERED INDEX [IX_PLAN_SUSCRIPCION_VIGENCIA] 
    ON [CORE].[PLAN_SUSCRIPCION] ([PLS_FECHA_INICIO_VIGENCIA], [PLS_FECHA_FIN_VIGENCIA]);
    PRINT 'Índice IX_PLAN_SUSCRIPCION_VIGENCIA creado.';
END
GO

-- =================================================================
-- Insertar datos de ejemplo (OPCIONAL - Comentado por defecto)
-- =================================================================
/*
-- Plan Básico
INSERT INTO [CORE].[PLAN_SUSCRIPCION] (
    [GYM_ID], [PLS_NOMBRE], [PLS_CODIGO], [PLS_DESCRIPCION], [PLS_PRECIO],
    [PLS_DURACION_DIAS], [PLS_LIMITE_ACCESOS_MES], [PLS_CLASES_GRUPALES_MES],
    [PLS_ACCESO_TODAS_SUCURSALES], [PLS_PERMITE_CONGELAR], [PLS_DIAS_MAX_CONGELAMIENTO],
    [PLS_PERMITE_INVITADOS], [PLS_INCLUYE_SPA], [PLS_INCLUYE_CASILLERO],
    [PLS_INCLUYE_ESTACIONAMIENTO], [PLS_INCLUYE_NUTRICION], [PLS_RENOVACION_AUTOMATICA],
    [PLS_REQUIERE_CONTRATO], [PLS_ORDEN], [PLS_ES_DESTACADO], [PLS_ESTADO]
)
VALUES (
    1, 'Básico', 'PLAN-BASICO', 'Acceso básico al gimnasio con accesos limitados', 299.00,
    30, 12, 4,
    0, 1, 7,
    0, 0, 0,
    0, 0, 1,
    0, 1, 0, 1
);

-- Plan Estándar
INSERT INTO [CORE].[PLAN_SUSCRIPCION] (
    [GYM_ID], [PLS_NOMBRE], [PLS_CODIGO], [PLS_DESCRIPCION], [PLS_PRECIO],
    [PLS_DURACION_DIAS], [PLS_CLASES_GRUPALES_MES],
    [PLS_ACCESO_TODAS_SUCURSALES], [PLS_PERMITE_CONGELAR], [PLS_DIAS_MAX_CONGELAMIENTO],
    [PLS_PERMITE_INVITADOS], [PLS_NUM_INVITADOS_MES], [PLS_INCLUYE_SPA], [PLS_INCLUYE_CASILLERO],
    [PLS_INCLUYE_ESTACIONAMIENTO], [PLS_INCLUYE_NUTRICION], [PLS_RENOVACION_AUTOMATICA],
    [PLS_REQUIERE_CONTRATO], [PLS_ORDEN], [PLS_ES_DESTACADO], [PLS_ESTADO]
)
VALUES (
    1, 'Estándar', 'PLAN-ESTANDAR', 'Acceso ilimitado con clases grupales incluidas', 499.00,
    30, NULL,
    0, 1, 14,
    1, 2, 0, 1,
    0, 0, 1,
    0, 2, 1, 1
);

-- Plan Premium
INSERT INTO [CORE].[PLAN_SUSCRIPCION] (
    [GYM_ID], [PLS_NOMBRE], [PLS_CODIGO], [PLS_DESCRIPCION], [PLS_PRECIO],
    [PLS_DURACION_DIAS], [PLS_SESIONES_ENTRENADOR],
    [PLS_ACCESO_TODAS_SUCURSALES], [PLS_PERMITE_CONGELAR], [PLS_DIAS_MAX_CONGELAMIENTO],
    [PLS_PERMITE_INVITADOS], [PLS_NUM_INVITADOS_MES], [PLS_INCLUYE_SPA], [PLS_INCLUYE_CASILLERO],
    [PLS_INCLUYE_ESTACIONAMIENTO], [PLS_INCLUYE_NUTRICION], [PLS_PRIORIDAD_RESERVAS],
    [PLS_RENOVACION_AUTOMATICA], [PLS_REQUIERE_CONTRATO], [PLS_ORDEN], [PLS_ES_DESTACADO], [PLS_ESTADO]
)
VALUES (
    1, 'Premium', 'PLAN-PREMIUM', 'Acceso completo con todas las amenidades y entrenador personal', 899.00,
    30, 4,
    1, 1, 30,
    1, 4, 1, 1,
    1, 1, 1,
    1, 0, 3, 0, 1
);

-- Plan VIP
INSERT INTO [CORE].[PLAN_SUSCRIPCION] (
    [GYM_ID], [PLS_NOMBRE], [PLS_CODIGO], [PLS_DESCRIPCION], [PLS_PRECIO],
    [PLS_DURACION_DIAS], [PLS_SESIONES_ENTRENADOR],
    [PLS_ACCESO_TODAS_SUCURSALES], [PLS_PERMITE_CONGELAR], [PLS_DIAS_MAX_CONGELAMIENTO],
    [PLS_PERMITE_INVITADOS], [PLS_NUM_INVITADOS_MES], [PLS_INCLUYE_SPA], [PLS_INCLUYE_CASILLERO],
    [PLS_INCLUYE_ESTACIONAMIENTO], [PLS_INCLUYE_NUTRICION], [PLS_PRIORIDAD_RESERVAS],
    [PLS_RENOVACION_AUTOMATICA], [PLS_REQUIERE_CONTRATO], [PLS_MESES_MIN_COMPROMISO],
    [PLS_ORDEN], [PLS_ES_DESTACADO], [PLS_ESTADO]
)
VALUES (
    1, 'VIP', 'PLAN-VIP', 'Plan exclusivo con todos los beneficios y atención personalizada', 1499.00,
    30, 8,
    1, 1, 60,
    1, NULL, 1, 1,
    1, 1, 1,
    1, 1, 12,
    4, 0, 1
);

-- Plan Estudiante
INSERT INTO [CORE].[PLAN_SUSCRIPCION] (
    [GYM_ID], [PLS_NOMBRE], [PLS_CODIGO], [PLS_DESCRIPCION], [PLS_PRECIO],
    [PLS_DURACION_DIAS], [PLS_CLASES_GRUPALES_MES], [PLS_DESCUENTO_PORCENTAJE],
    [PLS_ACCESO_TODAS_SUCURSALES], [PLS_PERMITE_CONGELAR], [PLS_DIAS_MAX_CONGELAMIENTO],
    [PLS_PERMITE_INVITADOS], [PLS_INCLUYE_SPA], [PLS_INCLUYE_CASILLERO],
    [PLS_INCLUYE_ESTACIONAMIENTO], [PLS_INCLUYE_NUTRICION], [PLS_RENOVACION_AUTOMATICA],
    [PLS_REQUIERE_CONTRATO], [PLS_ORDEN], [PLS_ES_DESTACADO], [PLS_ESTADO]
)
VALUES (
    1, 'Estudiante', 'PLAN-ESTUDIANTE', 'Plan especial con descuento para estudiantes', 349.00,
    30, 8, 25.00,
    0, 1, 7,
    0, 0, 0,
    0, 0, 1,
    0, 5, 0, 1
);

PRINT 'Datos de ejemplo insertados en CORE.PLAN_SUSCRIPCION.';
*/

PRINT '=================================================================';
PRINT 'Script de PLAN_SUSCRIPCION completado exitosamente.';
PRINT '=================================================================';
GO

