CREATE TABLE [GIMNASIO].[CALIFICACIONES_ENTRENADOR] (
    [CEN_ID]                    INT              IDENTITY (1, 1) NOT NULL,
    [CEN_GUID]                  UNIQUEIDENTIFIER NOT NULL,
    [ENT_ID]                    INT              NOT NULL,
    [PNA_ID]                    INT              NOT NULL,
    [CEN_CALIFICACION]          INT              NOT NULL,
    [CEN_COMENTARIO]            VARCHAR (2000)   NULL,
    [CEN_FECHA_CALIFICACION]    DATETIME         NOT NULL,
    [CEN_ESTADO]                BIT              NOT NULL,
    [CEN_FECHA_REGISTRO]        DATETIME         NULL,
    [USR_ID_REGISTRADOR]        INT              NULL
);
GO

ALTER TABLE [GIMNASIO].[CALIFICACIONES_ENTRENADOR]
    ADD CONSTRAINT [DEFAULT_CALIFICACIONES_ENTRENADOR_CEN_GUID] DEFAULT (newid()) FOR [CEN_GUID];
GO

ALTER TABLE [GIMNASIO].[CALIFICACIONES_ENTRENADOR]
    ADD CONSTRAINT [DEFAULT_CALIFICACIONES_ENTRENADOR_CEN_ESTADO] DEFAULT (1) FOR [CEN_ESTADO];
GO

ALTER TABLE [GIMNASIO].[CALIFICACIONES_ENTRENADOR]
    ADD CONSTRAINT [CHK_CALIFICACIONES_ENTRENADOR_CALIFICACION] CHECK ([CEN_CALIFICACION] >= 1 AND [CEN_CALIFICACION] <= 5);
GO

ALTER TABLE [GIMNASIO].[CALIFICACIONES_ENTRENADOR]
    ADD CONSTRAINT [PK_CALIFICACIONES_ENTRENADOR] PRIMARY KEY CLUSTERED ([CEN_ID] ASC);
GO

ALTER TABLE [GIMNASIO].[CALIFICACIONES_ENTRENADOR]
    ADD CONSTRAINT [FK_CALIFICACIONES_ENTRENADOR_ENTRENADORES] FOREIGN KEY ([ENT_ID]) REFERENCES [GIMNASIO].[ENTRENADORES] ([ENT_ID]);
GO

ALTER TABLE [GIMNASIO].[CALIFICACIONES_ENTRENADOR]
    ADD CONSTRAINT [FK_CALIFICACIONES_ENTRENADOR_PERSONA] FOREIGN KEY ([PNA_ID]) REFERENCES [AUTENTICACION].[PERSONA] ([PNA_ID]);
GO

ALTER TABLE [GIMNASIO].[CALIFICACIONES_ENTRENADOR]
    ADD CONSTRAINT [FK_CALIFICACIONES_ENTRENADOR_USUARIO_REGISTRADOR] FOREIGN KEY ([USR_ID_REGISTRADOR]) REFERENCES [AUTENTICACION].[USUARIO] ([USR_ID]);
GO

EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'Tabla de Calificaciones de Entrenador', @level0type = N'SCHEMA', @level0name = N'GIMNASIO', @level1type = N'TABLE', @level1name = N'CALIFICACIONES_ENTRENADOR';
GO
