CREATE TABLE [GIMNASIO].[CLASES_GRUPALES] (
    [CGR_ID]                  INT              IDENTITY (1, 1) NOT NULL,
    [CGR_GUID]                UNIQUEIDENTIFIER NOT NULL,
    [GYM_ID]                  INT              NOT NULL,
    [ENT_ID]                  INT              NOT NULL,
    [CGR_NOMBRE_CLASE]        VARCHAR (200)    NOT NULL,
    [CGR_DESCRIPCION_CLASE]   VARCHAR (1000)   NULL,
    [CGR_DURACION_MINUTOS]    INT              NOT NULL,
    [CGR_CAPACIDAD_MAXIMA]    INT              NOT NULL,
    [CGR_URL_IMAGEN_CLASE]    VARCHAR (500)    NULL,
    [CGR_ESTADO]              BIT              NOT NULL,
    [CGR_FECHA_REGISTRO]      DATETIME         NULL,
    [USR_ID_REGISTRADOR]      INT              NULL
);
GO

ALTER TABLE [GIMNASIO].[CLASES_GRUPALES]
    ADD CONSTRAINT [DEFAULT_CLASES_GRUPALES_CGR_GUID] DEFAULT (newid()) FOR [CGR_GUID];
GO

ALTER TABLE [GIMNASIO].[CLASES_GRUPALES]
    ADD CONSTRAINT [DEFAULT_CLASES_GRUPALES_CGR_ESTADO] DEFAULT (1) FOR [CGR_ESTADO];
GO

ALTER TABLE [GIMNASIO].[CLASES_GRUPALES]
    ADD CONSTRAINT [PK_CLASES_GRUPALES] PRIMARY KEY CLUSTERED ([CGR_ID] ASC);
GO

ALTER TABLE [GIMNASIO].[CLASES_GRUPALES]
    ADD CONSTRAINT [FK_CLASES_GRUPALES_GIMNASIO] FOREIGN KEY ([GYM_ID]) REFERENCES [GIMNASIO].[GIMNASIO] ([GYM_ID]);
GO

ALTER TABLE [GIMNASIO].[CLASES_GRUPALES]
    ADD CONSTRAINT [FK_CLASES_GRUPALES_ENTRENADORES] FOREIGN KEY ([ENT_ID]) REFERENCES [GIMNASIO].[ENTRENADORES] ([ENT_ID]);
GO

ALTER TABLE [GIMNASIO].[CLASES_GRUPALES]
    ADD CONSTRAINT [FK_CLASES_GRUPALES_USUARIO_REGISTRADOR] FOREIGN KEY ([USR_ID_REGISTRADOR]) REFERENCES [AUTENTICACION].[USUARIO] ([USR_ID]);
GO

EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'Tabla de Clases Grupales', @level0type = N'SCHEMA', @level0name = N'GIMNASIO', @level1type = N'TABLE', @level1name = N'CLASES_GRUPALES';
GO
