CREATE TABLE [GIMNASIO].[ENTRENADORES] (
    [ENT_ID]                  INT              IDENTITY (1, 1) NOT NULL,
    [ENT_GUID]                UNIQUEIDENTIFIER NOT NULL,
    [PNA_ID]                  INT              NOT NULL,
    [GYM_ID]                  INT              NOT NULL,
    [ENT_ESPECIALIDAD]        VARCHAR (200)    NULL,
    [ENT_BIOGRAFIA]           VARCHAR (2000)   NULL,
    [ENT_URL_FOTO_PERFIL]     VARCHAR (500)    NULL,
    [ENT_ESTADO]              BIT              NOT NULL,
    [ENT_FECHA_REGISTRO]      DATETIME         NULL,
    [USR_ID_REGISTRADOR]      INT              NULL
);
GO

ALTER TABLE [GIMNASIO].[ENTRENADORES]
    ADD CONSTRAINT [DEFAULT_ENTRENADORES_ENT_GUID] DEFAULT (newid()) FOR [ENT_GUID];
GO

ALTER TABLE [GIMNASIO].[ENTRENADORES]
    ADD CONSTRAINT [DEFAULT_ENTRENADORES_ENT_ESTADO] DEFAULT (1) FOR [ENT_ESTADO];
GO

ALTER TABLE [GIMNASIO].[ENTRENADORES]
    ADD CONSTRAINT [PK_ENTRENADORES] PRIMARY KEY CLUSTERED ([ENT_ID] ASC);
GO

ALTER TABLE [GIMNASIO].[ENTRENADORES]
    ADD CONSTRAINT [FK_ENTRENADORES_PERSONA] FOREIGN KEY ([PNA_ID]) REFERENCES [AUTENTICACION].[PERSONA] ([PNA_ID]);
GO

ALTER TABLE [GIMNASIO].[ENTRENADORES]
    ADD CONSTRAINT [FK_ENTRENADORES_GIMNASIO] FOREIGN KEY ([GYM_ID]) REFERENCES [GIMNASIO].[GIMNASIO] ([GYM_ID]);
GO

ALTER TABLE [GIMNASIO].[ENTRENADORES]
    ADD CONSTRAINT [FK_ENTRENADORES_USUARIO_REGISTRADOR] FOREIGN KEY ([USR_ID_REGISTRADOR]) REFERENCES [AUTENTICACION].[USUARIO] ([USR_ID]);
GO

EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'Tabla de Entrenadores', @level0type = N'SCHEMA', @level0name = N'GIMNASIO', @level1type = N'TABLE', @level1name = N'ENTRENADORES';
GO
