CREATE TABLE [GIMNASIO].[HORARIOS_CLASE] (
    [HCL_ID]                INT              IDENTITY (1, 1) NOT NULL,
    [HCL_GUID]              UNIQUEIDENTIFIER NOT NULL,
    [CGR_ID]                INT              NOT NULL,
    [HCL_DIA_SEMANA]        VARCHAR (20)     NOT NULL,
    [HCL_HORA_INICIO]       TIME             NOT NULL,
    [HCL_HORA_FIN]          TIME             NOT NULL,
    [HCL_UBICACION_SALA]    VARCHAR (100)    NULL,
    [HCL_ESTADO]            BIT              NOT NULL,
    [HCL_FECHA_REGISTRO]    DATETIME         NULL,
    [USR_ID_REGISTRADOR]    INT              NULL
);
GO

ALTER TABLE [GIMNASIO].[HORARIOS_CLASE]
    ADD CONSTRAINT [DEFAULT_HORARIOS_CLASE_HCL_GUID] DEFAULT (newid()) FOR [HCL_GUID];
GO

ALTER TABLE [GIMNASIO].[HORARIOS_CLASE]
    ADD CONSTRAINT [DEFAULT_HORARIOS_CLASE_HCL_ESTADO] DEFAULT (1) FOR [HCL_ESTADO];
GO

ALTER TABLE [GIMNASIO].[HORARIOS_CLASE]
    ADD CONSTRAINT [PK_HORARIOS_CLASE] PRIMARY KEY CLUSTERED ([HCL_ID] ASC);
GO

ALTER TABLE [GIMNASIO].[HORARIOS_CLASE]
    ADD CONSTRAINT [FK_HORARIOS_CLASE_CLASES_GRUPALES] FOREIGN KEY ([CGR_ID]) REFERENCES [GIMNASIO].[CLASES_GRUPALES] ([CGR_ID]);
GO

ALTER TABLE [GIMNASIO].[HORARIOS_CLASE]
    ADD CONSTRAINT [FK_HORARIOS_CLASE_USUARIO_REGISTRADOR] FOREIGN KEY ([USR_ID_REGISTRADOR]) REFERENCES [AUTENTICACION].[USUARIO] ([USR_ID]);
GO

EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'Tabla de Horarios de Clase', @level0type = N'SCHEMA', @level0name = N'GIMNASIO', @level1type = N'TABLE', @level1name = N'HORARIOS_CLASE';
GO
