CREATE TABLE [GIMNASIO].[MAQUINAS_GIMNASIO] (
    [MGY_ID]                    INT              IDENTITY (1, 1) NOT NULL,
    [MGY_GUID]                  UNIQUEIDENTIFIER NOT NULL,
    [GYM_ID]                    INT              NOT NULL,
    [MGY_NOMBRE_MAQUINA]        VARCHAR (200)    NOT NULL,
    [MGY_TIPO_MAQUINA]          VARCHAR (100)    NOT NULL,
    [MGY_URL_IMAGEN_MAQUINA]    VARCHAR (500)    NULL,
    [MGY_ESTADO_MAQUINA]        VARCHAR (50)     NOT NULL,
    [MGY_ULTIMA_REVISION]       DATETIME         NULL,
    [MGY_ESTADO]                BIT              NOT NULL,
    [MGY_FECHA_REGISTRO]        DATETIME         NULL,
    [USR_ID_REGISTRADOR]        INT              NULL
);
GO

ALTER TABLE [GIMNASIO].[MAQUINAS_GIMNASIO]
    ADD CONSTRAINT [DEFAULT_MAQUINAS_GIMNASIO_MGY_GUID] DEFAULT (newid()) FOR [MGY_GUID];
GO

ALTER TABLE [GIMNASIO].[MAQUINAS_GIMNASIO]
    ADD CONSTRAINT [DEFAULT_MAQUINAS_GIMNASIO_MGY_ESTADO] DEFAULT (1) FOR [MGY_ESTADO];
GO

ALTER TABLE [GIMNASIO].[MAQUINAS_GIMNASIO]
    ADD CONSTRAINT [PK_MAQUINAS_GIMNASIO] PRIMARY KEY CLUSTERED ([MGY_ID] ASC);
GO

ALTER TABLE [GIMNASIO].[MAQUINAS_GIMNASIO]
    ADD CONSTRAINT [FK_MAQUINAS_GIMNASIO_GIMNASIO] FOREIGN KEY ([GYM_ID]) REFERENCES [GIMNASIO].[GIMNASIO] ([GYM_ID]);
GO

ALTER TABLE [GIMNASIO].[MAQUINAS_GIMNASIO]
    ADD CONSTRAINT [FK_MAQUINAS_GIMNASIO_USUARIO_REGISTRADOR] FOREIGN KEY ([USR_ID_REGISTRADOR]) REFERENCES [AUTENTICACION].[USUARIO] ([USR_ID]);
GO

EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'Tabla de Máquinas de Gimnasio', @level0type = N'SCHEMA', @level0name = N'GIMNASIO', @level1type = N'TABLE', @level1name = N'MAQUINAS_GIMNASIO';
GO
