CREATE TABLE [GIMNASIO].[OBJETIVOS_PERSONALES] (
    [OBP_ID]                      INT              IDENTITY (1, 1) NOT NULL,
    [OBP_GUID]                    UNIQUEIDENTIFIER NOT NULL,
    [PNA_ID]                      INT              NOT NULL,
    [OBP_TIPO_OBJETIVO]           VARCHAR (100)    NOT NULL,
    [OBP_VALOR_INICIAL]           DECIMAL (18, 2)  NULL,
    [OBP_VALOR_OBJETIVO]          DECIMAL (18, 2)  NOT NULL,
    [OBP_FECHA_INICIO_OBJETIVO]   DATETIME         NOT NULL,
    [OBP_FECHA_FIN_ESTIMADA]      DATETIME         NULL,
    [OBP_ESTADO_OBJETIVO]         VARCHAR (50)     NOT NULL,
    [OBP_DESCRIPCION]             VARCHAR (1000)   NULL,
    [OBP_FECHA_REGISTRO]          DATETIME         NULL,
    [USR_ID_REGISTRADOR]          INT              NULL
);
GO

ALTER TABLE [GIMNASIO].[OBJETIVOS_PERSONALES]
    ADD CONSTRAINT [DEFAULT_OBJETIVOS_PERSONALES_OBP_GUID] DEFAULT (newid()) FOR [OBP_GUID];
GO

ALTER TABLE [GIMNASIO].[OBJETIVOS_PERSONALES]
    ADD CONSTRAINT [PK_OBJETIVOS_PERSONALES] PRIMARY KEY CLUSTERED ([OBP_ID] ASC);
GO

ALTER TABLE [GIMNASIO].[OBJETIVOS_PERSONALES]
    ADD CONSTRAINT [FK_OBJETIVOS_PERSONALES_PERSONA] FOREIGN KEY ([PNA_ID]) REFERENCES [AUTENTICACION].[PERSONA] ([PNA_ID]);
GO

ALTER TABLE [GIMNASIO].[OBJETIVOS_PERSONALES]
    ADD CONSTRAINT [FK_OBJETIVOS_PERSONALES_USUARIO_REGISTRADOR] FOREIGN KEY ([USR_ID_REGISTRADOR]) REFERENCES [AUTENTICACION].[USUARIO] ([USR_ID]);
GO

EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'Tabla de Objetivos Personales', @level0type = N'SCHEMA', @level0name = N'GIMNASIO', @level1type = N'TABLE', @level1name = N'OBJETIVOS_PERSONALES';
GO
