CREATE TABLE [GIMNASIO].[RESENAS_GIMNASIO] (
    [RGY_ID]                INT              IDENTITY (1, 1) NOT NULL,
    [RGY_GUID]              UNIQUEIDENTIFIER NOT NULL,
    [GYM_ID]                INT              NOT NULL,
    [PNA_ID]                INT              NOT NULL,
    [RGY_CALIFICACION]      INT              NOT NULL,
    [RGY_COMENTARIO]        VARCHAR (2000)   NULL,
    [RGY_FECHA_RESENA]      DATETIME         NOT NULL,
    [RGY_ESTADO]            BIT              NOT NULL,
    [RGY_FECHA_REGISTRO]    DATETIME         NULL,
    [USR_ID_REGISTRADOR]    INT              NULL
);
GO

ALTER TABLE [GIMNASIO].[RESENAS_GIMNASIO]
    ADD CONSTRAINT [DEFAULT_RESENAS_GIMNASIO_RGY_GUID] DEFAULT (newid()) FOR [RGY_GUID];
GO

ALTER TABLE [GIMNASIO].[RESENAS_GIMNASIO]
    ADD CONSTRAINT [DEFAULT_RESENAS_GIMNASIO_RGY_ESTADO] DEFAULT (1) FOR [RGY_ESTADO];
GO

ALTER TABLE [GIMNASIO].[RESENAS_GIMNASIO]
    ADD CONSTRAINT [CHK_RESENAS_GIMNASIO_CALIFICACION] CHECK ([RGY_CALIFICACION] >= 1 AND [RGY_CALIFICACION] <= 5);
GO

ALTER TABLE [GIMNASIO].[RESENAS_GIMNASIO]
    ADD CONSTRAINT [PK_RESENAS_GIMNASIO] PRIMARY KEY CLUSTERED ([RGY_ID] ASC);
GO

ALTER TABLE [GIMNASIO].[RESENAS_GIMNASIO]
    ADD CONSTRAINT [FK_RESENAS_GIMNASIO_GIMNASIO] FOREIGN KEY ([GYM_ID]) REFERENCES [GIMNASIO].[GIMNASIO] ([GYM_ID]);
GO

ALTER TABLE [GIMNASIO].[RESENAS_GIMNASIO]
    ADD CONSTRAINT [FK_RESENAS_GIMNASIO_PERSONA] FOREIGN KEY ([PNA_ID]) REFERENCES [AUTENTICACION].[PERSONA] ([PNA_ID]);
GO

ALTER TABLE [GIMNASIO].[RESENAS_GIMNASIO]
    ADD CONSTRAINT [FK_RESENAS_GIMNASIO_USUARIO_REGISTRADOR] FOREIGN KEY ([USR_ID_REGISTRADOR]) REFERENCES [AUTENTICACION].[USUARIO] ([USR_ID]);
GO

EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'Tabla de Reseñas de Gimnasio', @level0type = N'SCHEMA', @level0name = N'GIMNASIO', @level1type = N'TABLE', @level1name = N'RESENAS_GIMNASIO';
GO
