CREATE TABLE [GIMNASIO].[RESERVAS_CLASE] (
    [RCL_ID]                INT              IDENTITY (1, 1) NOT NULL,
    [RCL_GUID]              UNIQUEIDENTIFIER NOT NULL,
    [HCL_ID]                INT              NOT NULL,
    [PNA_ID]                INT              NOT NULL,
    [RCL_FECHA_RESERVA]     DATETIME         NOT NULL,
    [RCL_ESTADO_RESERVA]    VARCHAR (50)     NOT NULL,
    [RCL_FECHA_REGISTRO]    DATETIME         NULL,
    [USR_ID_REGISTRADOR]    INT              NULL
);
GO

ALTER TABLE [GIMNASIO].[RESERVAS_CLASE]
    ADD CONSTRAINT [DEFAULT_RESERVAS_CLASE_RCL_GUID] DEFAULT (newid()) FOR [RCL_GUID];
GO

ALTER TABLE [GIMNASIO].[RESERVAS_CLASE]
    ADD CONSTRAINT [PK_RESERVAS_CLASE] PRIMARY KEY CLUSTERED ([RCL_ID] ASC);
GO

ALTER TABLE [GIMNASIO].[RESERVAS_CLASE]
    ADD CONSTRAINT [FK_RESERVAS_CLASE_HORARIOS_CLASE] FOREIGN KEY ([HCL_ID]) REFERENCES [GIMNASIO].[HORARIOS_CLASE] ([HCL_ID]);
GO

ALTER TABLE [GIMNASIO].[RESERVAS_CLASE]
    ADD CONSTRAINT [FK_RESERVAS_CLASE_PERSONA] FOREIGN KEY ([PNA_ID]) REFERENCES [AUTENTICACION].[PERSONA] ([PNA_ID]);
GO

ALTER TABLE [GIMNASIO].[RESERVAS_CLASE]
    ADD CONSTRAINT [FK_RESERVAS_CLASE_USUARIO_REGISTRADOR] FOREIGN KEY ([USR_ID_REGISTRADOR]) REFERENCES [AUTENTICACION].[USUARIO] ([USR_ID]);
GO

EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'Tabla de Reservas de Clase', @level0type = N'SCHEMA', @level0name = N'GIMNASIO', @level1type = N'TABLE', @level1name = N'RESERVAS_CLASE';
GO
