CREATE TABLE [GIMNASIO].[VIDEOS_GIMNASIO] (
    [VGY_ID]              INT              IDENTITY (1, 1) NOT NULL,
    [VGY_GUID]            UNIQUEIDENTIFIER NOT NULL,
    [GYM_ID]              INT              NOT NULL,
    [VGY_URL_VIDEO]       VARCHAR (500)    NOT NULL,
    [VGY_TITULO]          VARCHAR (200)    NOT NULL,
    [VGY_DESCRIPCION]     VARCHAR (1000)   NULL,
    [VGY_ESTADO]          BIT              NOT NULL,
    [VGY_FECHA_REGISTRO]  DATETIME         NULL,
    [USR_ID_REGISTRADOR]  INT              NULL
);
GO

ALTER TABLE [GIMNASIO].[VIDEOS_GIMNASIO]
    ADD CONSTRAINT [DEFAULT_VIDEOS_GIMNASIO_VGY_GUID] DEFAULT (newid()) FOR [VGY_GUID];
GO

ALTER TABLE [GIMNASIO].[VIDEOS_GIMNASIO]
    ADD CONSTRAINT [DEFAULT_VIDEOS_GIMNASIO_VGY_ESTADO] DEFAULT (1) FOR [VGY_ESTADO];
GO

ALTER TABLE [GIMNASIO].[VIDEOS_GIMNASIO]
    ADD CONSTRAINT [PK_VIDEOS_GIMNASIO] PRIMARY KEY CLUSTERED ([VGY_ID] ASC);
GO

ALTER TABLE [GIMNASIO].[VIDEOS_GIMNASIO]
    ADD CONSTRAINT [FK_VIDEOS_GIMNASIO_GIMNASIO] FOREIGN KEY ([GYM_ID]) REFERENCES [GIMNASIO].[GIMNASIO] ([GYM_ID]);
GO

ALTER TABLE [GIMNASIO].[VIDEOS_GIMNASIO]
    ADD CONSTRAINT [FK_VIDEOS_GIMNASIO_USUARIO_REGISTRADOR] FOREIGN KEY ([USR_ID_REGISTRADOR]) REFERENCES [AUTENTICACION].[USUARIO] ([USR_ID]);
GO

EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'Tabla de Videos de Gimnasio', @level0type = N'SCHEMA', @level0name = N'GIMNASIO', @level1type = N'TABLE', @level1name = N'VIDEOS_GIMNASIO';
GO
