global using AutoMapper;
global using Common.Clock;
global using Common.Messages;
global using Common.PluginFactory.Interface;
global using Common.Security.Model;
global using Common.Utils.CustomExceptions;
global using Common.Utils.Extensions;
global using Common.WebApi.Models;
global using MediatR;
global using Microsoft.Extensions.Logging;
global using PersistenceDb.Repository.Interfaces.UnitOfWork;
global using Common.WebApi.Models.Enum;
global using Common.Utils.ConstansCodes;
global using PersistenceDb.Models.Enums;
global using LogicApi.Model.Response;
global using EnumDataBase = PersistenceDb.Models.Enums;
global using EnumCommonCop = Common.Cooperative.Models.Enums;
global using EnumLogicApi = LogicApi.Model.Enum;
global using EnumLogicCommon = LogicCommon.Model.Enum;
global using EnumCommon = Common.WebCommon.Models.Enum;
