GO
INSERT INTO [ADMINISTRACION].[PAIS] (PAI_CODIGO, PAI_NOMBRE, PAI_ESTADO)
VALUES ('ECU', 'Ecuador', 1);
GO
INSERT INTO [ADMINISTRACION].[REGION] (REG_CODIGO, REG_NOMBRE, PAI_ID, REG_ESTADO)
SELECT 'COSTA', 'Costa', PAI_ID, 1 FROM [ADMINISTRACION].[PAIS] WHERE PAI_CODIGO = 'ECU'
UNION ALL
SELECT 'SIERRA', 'Sierra', PAI_ID, 1 FROM [ADMINISTRACION].[PAIS] WHERE PAI_CODIGO = 'ECU'
UNION ALL
SELECT 'ORIENTE', 'Oriente', PAI_ID, 1 FROM [ADMINISTRACION].[PAIS] WHERE PAI_CODIGO = 'ECU'
UNION ALL
SELECT 'INSULAR', 'Insular', PAI_ID, 1 FROM [ADMINISTRACION].[PAIS] WHERE PAI_CODIGO = 'ECU';
GO
INSERT INTO [ADMINISTRACION].[PROVINCIA] (PRO_CODIGO, PRO_NOMBRE, REG_ID, PRO_ESTADO)
SELECT 'AZU', 'Azuay', REG_ID, 1 FROM [ADMINISTRACION].[REGION] WHERE REG_CODIGO = 'SIERRA'
UNION ALL
SELECT 'BOL', 'Bolívar', REG_ID, 1 FROM [ADMINISTRACION].[REGION] WHERE REG_CODIGO = 'SIERRA'
UNION ALL
SELECT 'CAN', 'Cañar', REG_ID, 1 FROM [ADMINISTRACION].[REGION] WHERE REG_CODIGO = 'SIERRA'
UNION ALL
SELECT 'CAR', 'Carchi', REG_ID, 1 FROM [ADMINISTRACION].[REGION] WHERE REG_CODIGO = 'SIERRA'
UNION ALL
SELECT 'CHI', 'Chimborazo', REG_ID, 1 FROM [ADMINISTRACION].[REGION] WHERE REG_CODIGO = 'SIERRA'
UNION ALL
SELECT 'COT', 'Cotopaxi', REG_ID, 1 FROM [ADMINISTRACION].[REGION] WHERE REG_CODIGO = 'SIERRA'
UNION ALL
SELECT 'EOR', 'El Oro', REG_ID, 1 FROM [ADMINISTRACION].[REGION] WHERE REG_CODIGO = 'COSTA'
UNION ALL
SELECT 'ESM', 'Esmeraldas', REG_ID, 1 FROM [ADMINISTRACION].[REGION] WHERE REG_CODIGO = 'COSTA'
UNION ALL
SELECT 'GAL', 'Galápagos', REG_ID, 1 FROM [ADMINISTRACION].[REGION] WHERE REG_CODIGO = 'INSULAR'
UNION ALL
SELECT 'GUA', 'Guayas', REG_ID, 1 FROM [ADMINISTRACION].[REGION] WHERE REG_CODIGO = 'COSTA'
UNION ALL
SELECT 'IMB', 'Imbabura', REG_ID, 1 FROM [ADMINISTRACION].[REGION] WHERE REG_CODIGO = 'SIERRA'
UNION ALL
SELECT 'LOJ', 'Loja', REG_ID, 1 FROM [ADMINISTRACION].[REGION] WHERE REG_CODIGO = 'SIERRA'
UNION ALL
SELECT 'LRO', 'Los Ríos', REG_ID, 1 FROM [ADMINISTRACION].[REGION] WHERE REG_CODIGO = 'COSTA'
UNION ALL
SELECT 'MAN', 'Manabí', REG_ID, 1 FROM [ADMINISTRACION].[REGION] WHERE REG_CODIGO = 'COSTA'
UNION ALL
SELECT 'MSA', 'Morona Santiago', REG_ID, 1 FROM [ADMINISTRACION].[REGION] WHERE REG_CODIGO = 'ORIENTE'
UNION ALL
SELECT 'NAP', 'Napo', REG_ID, 1 FROM [ADMINISTRACION].[REGION] WHERE REG_CODIGO = 'ORIENTE'
UNION ALL
SELECT 'ORE', 'Orellana', REG_ID, 1 FROM [ADMINISTRACION].[REGION] WHERE REG_CODIGO = 'ORIENTE'
UNION ALL
SELECT 'PAS', 'Pastaza', REG_ID, 1 FROM [ADMINISTRACION].[REGION] WHERE REG_CODIGO = 'ORIENTE'
UNION ALL
SELECT 'PIC', 'Pichincha', REG_ID, 1 FROM [ADMINISTRACION].[REGION] WHERE REG_CODIGO = 'SIERRA'
UNION ALL
SELECT 'SUC', 'Sucumbíos', REG_ID, 1 FROM [ADMINISTRACION].[REGION] WHERE REG_CODIGO = 'ORIENTE'
UNION ALL
SELECT 'SEN', 'Santa Elena', REG_ID, 1 FROM [ADMINISTRACION].[REGION] WHERE REG_CODIGO = 'COSTA'
UNION ALL
SELECT 'SDT', 'Santo Domingo de los Tsáchilas', REG_ID, 1 FROM [ADMINISTRACION].[REGION] WHERE REG_CODIGO = 'COSTA'
UNION ALL
SELECT 'TUN', 'Tungurahua', REG_ID, 1 FROM [ADMINISTRACION].[REGION] WHERE REG_CODIGO = 'SIERRA'
UNION ALL
SELECT 'ZCH', 'Zamora Chinchipe', REG_ID, 1 FROM [ADMINISTRACION].[REGION] WHERE REG_CODIGO = 'ORIENTE';


GO

-- Azuay
INSERT INTO [ADMINISTRACION].[LUGAR] (LOD_CODIGO_LUGAR, LOD_NOMBRE, LOD_NOMBRE_CORTO, LOD_ESTADO, LOD_UBICACION_LATITUD, LOD_UBICACION_LONGITUD, PRO_ID)
SELECT 'CUENCA', 'Cuenca', 'Cuenca', 1, -2.90055, -79.00453, PRO_ID FROM [ADMINISTRACION].[PROVINCIA] WHERE PRO_CODIGO = 'AZU'
UNION ALL
SELECT 'PARQUE_CAJAS', 'Parque Nacional Cajas', 'Cajas', 1, -2.8324, -79.2247, PRO_ID FROM [ADMINISTRACION].[PROVINCIA] WHERE PRO_CODIGO = 'AZU'
UNION ALL
SELECT 'TURI', 'Mirador de Turi', 'Turi', 1, -2.8974, -78.9996, PRO_ID FROM [ADMINISTRACION].[PROVINCIA] WHERE PRO_CODIGO = 'AZU';

-- Bolívar
INSERT INTO [ADMINISTRACION].[LUGAR] (LOD_CODIGO_LUGAR, LOD_NOMBRE, LOD_NOMBRE_CORTO, LOD_ESTADO, LOD_UBICACION_LATITUD, LOD_UBICACION_LONGITUD, PRO_ID)
SELECT 'GUARANDA', 'Guaranda', 'Guaranda', 1, -1.712, -78.929, PRO_ID FROM [ADMINISTRACION].[PROVINCIA] WHERE PRO_CODIGO = 'BOL'
UNION ALL
SELECT 'CASCADAS_EL_ZARUMA', 'Cascadas de Zaruma', 'Zaruma', 1, -2.1531, -79.5752, PRO_ID FROM [ADMINISTRACION].[PROVINCIA] WHERE PRO_CODIGO = 'BOL'
UNION ALL
SELECT 'CULTURA_BOLIVAR', 'Cultura Bolívar', 'Cultura', 1, -1.6782, -78.9125, PRO_ID FROM [ADMINISTRACION].[PROVINCIA] WHERE PRO_CODIGO = 'BOL';

-- Cañar
INSERT INTO [ADMINISTRACION].[LUGAR] (LOD_CODIGO_LUGAR, LOD_NOMBRE, LOD_NOMBRE_CORTO, LOD_ESTADO, LOD_UBICACION_LATITUD, LOD_UBICACION_LONGITUD, PRO_ID)
SELECT 'AZOGUES', 'Azogues', 'Azogues', 1, -2.7364, -78.8406, PRO_ID FROM [ADMINISTRACION].[PROVINCIA] WHERE PRO_CODIGO = 'CAN'
UNION ALL
SELECT 'INGAPIRCA', 'Ingapirca', 'Ingapirca', 1, -2.6402, -78.7791, PRO_ID FROM [ADMINISTRACION].[PROVINCIA] WHERE PRO_CODIGO = 'CAN'
UNION ALL
SELECT 'BALNEARIO_CUMBE', 'Balneario Cumbe', 'Cumbe', 1, -2.7101, -78.8132, PRO_ID FROM [ADMINISTRACION].[PROVINCIA] WHERE PRO_CODIGO = 'CAN';

-- Carchi
INSERT INTO [ADMINISTRACION].[LUGAR] (LOD_CODIGO_LUGAR, LOD_NOMBRE, LOD_NOMBRE_CORTO, LOD_ESTADO, LOD_UBICACION_LATITUD, LOD_UBICACION_LONGITUD, PRO_ID)
SELECT 'TULCAN', 'Tulcán', 'Tulcán', 1, 0.814, -77.717, PRO_ID FROM [ADMINISTRACION].[PROVINCIA] WHERE PRO_CODIGO = 'CAR'
UNION ALL
SELECT 'PARQUE_NACIONAL_EL_COTO', 'Parque Nacional El Coto', 'Coto', 1, 0.847, -77.818, PRO_ID FROM [ADMINISTRACION].[PROVINCIA] WHERE PRO_CODIGO = 'CAR'
UNION ALL
SELECT 'LA_IGLESIA_DE_TULCAN', 'La Iglesia de Tulcán', 'Iglesia', 1, 0.814, -77.717, PRO_ID FROM [ADMINISTRACION].[PROVINCIA] WHERE PRO_CODIGO = 'CAR';

-- Chimborazo
INSERT INTO [ADMINISTRACION].[LUGAR] (LOD_CODIGO_LUGAR, LOD_NOMBRE, LOD_NOMBRE_CORTO, LOD_ESTADO, LOD_UBICACION_LATITUD, LOD_UBICACION_LONGITUD, PRO_ID)
SELECT 'RIOBAMBA', 'Riobamba', 'Riobamba', 1, -1.6644, -78.6273, PRO_ID FROM [ADMINISTRACION].[PROVINCIA] WHERE PRO_CODIGO = 'CHI'
UNION ALL
SELECT 'PICO_CHIMBORAZO', 'Pico Chimborazo', 'Chimborazo', 1, -1.4697, -78.8186, PRO_ID FROM [ADMINISTRACION].[PROVINCIA] WHERE PRO_CODIGO = 'CHI'
UNION ALL
SELECT 'CIUDAD_DE_RIOBAMBA', 'Ciudad de Riobamba', 'Ciudad', 1, -1.6644, -78.6273, PRO_ID FROM [ADMINISTRACION].[PROVINCIA] WHERE PRO_CODIGO = 'CHI';

-- Esmeraldas
INSERT INTO [ADMINISTRACION].[LUGAR] (LOD_CODIGO_LUGAR, LOD_NOMBRE, LOD_NOMBRE_CORTO, LOD_ESTADO, LOD_UBICACION_LATITUD, LOD_UBICACION_LONGITUD, PRO_ID)
SELECT 'ESMERALDAS', 'Esmeraldas', 'Esmeraldas', 1, 0.459, -79.5735, PRO_ID FROM [ADMINISTRACION].[PROVINCIA] WHERE PRO_CODIGO = 'ESM'
UNION ALL
SELECT 'TONSUPA', 'Tonsupa', 'Tonsupa', 1, 0.9927, -79.3366, PRO_ID FROM [ADMINISTRACION].[PROVINCIA] WHERE PRO_CODIGO = 'ESM'
UNION ALL
SELECT 'MONTALVO', 'Montalvo', 'Montalvo', 1, 0.969, -79.4525, PRO_ID FROM [ADMINISTRACION].[PROVINCIA] WHERE PRO_CODIGO = 'ESM';

-- Guayas
INSERT INTO [ADMINISTRACION].[LUGAR] (LOD_CODIGO_LUGAR, LOD_NOMBRE, LOD_NOMBRE_CORTO, LOD_ESTADO, LOD_UBICACION_LATITUD, LOD_UBICACION_LONGITUD, PRO_ID)
SELECT 'GUAYAQUIL', 'Guayaquil', 'Guayaquil', 1, -2.1701, -79.9226, PRO_ID FROM [ADMINISTRACION].[PROVINCIA] WHERE PRO_CODIGO = 'GUA'
UNION ALL
SELECT 'PARQUE_SAMANES', 'Parque Samanes', 'Samanes', 1, -2.1583, -79.9606, PRO_ID FROM [ADMINISTRACION].[PROVINCIA] WHERE PRO_CODIGO = 'GUA'
UNION ALL
SELECT 'ISLA_SAN_CRISTOBAL', 'Isla San Cristóbal', 'Isla', 1, -0.913, -89.4374, PRO_ID FROM [ADMINISTRACION].[PROVINCIA] WHERE PRO_CODIGO = 'GUA';


-- Imbabura
INSERT INTO [ADMINISTRACION].[LUGAR] (LOD_CODIGO_LUGAR, LOD_NOMBRE, LOD_NOMBRE_CORTO, LOD_ESTADO, LOD_UBICACION_LATITUD, LOD_UBICACION_LONGITUD, PRO_ID)
SELECT 'IBARRA', 'Ibarra', 'Ibarra', 1, 0.999, -78.1156, PRO_ID FROM [ADMINISTRACION].[PROVINCIA] WHERE PRO_CODIGO = 'IMB'
UNION ALL
SELECT 'LAGO_SAN_PABLO', 'Lago San Pablo', 'San Pablo', 1, 0.3378, -78.1007, PRO_ID FROM [ADMINISTRACION].[PROVINCIA] WHERE PRO_CODIGO = 'IMB'
UNION ALL
SELECT 'COTACACHI', 'Cotacachi', 'Cotacachi', 1, 0.253, -78.2444, PRO_ID FROM [ADMINISTRACION].[PROVINCIA] WHERE PRO_CODIGO = 'IMB';

-- Loja
INSERT INTO [ADMINISTRACION].[LUGAR] (LOD_CODIGO_LUGAR, LOD_NOMBRE, LOD_NOMBRE_CORTO, LOD_ESTADO, LOD_UBICACION_LATITUD, LOD_UBICACION_LONGITUD, PRO_ID)
SELECT 'LOJA', 'Loja', 'Loja', 1, -3.9907, -79.2041, PRO_ID FROM [ADMINISTRACION].[PROVINCIA] WHERE PRO_CODIGO = 'LOJ'
UNION ALL
SELECT 'CASCADA_DE_EL_PLATO', 'Cascada de El Plato', 'El Plato', 1, -4.0051, -79.1833, PRO_ID FROM [ADMINISTRACION].[PROVINCIA] WHERE PRO_CODIGO = 'LOJ'
UNION ALL
SELECT 'VALLENATOS', 'Vallenatos', 'Vallenatos', 1, -3.9865, -79.2062, PRO_ID FROM [ADMINISTRACION].[PROVINCIA] WHERE PRO_CODIGO = 'LOJ';

-- Manabí
INSERT INTO [ADMINISTRACION].[LUGAR] (LOD_CODIGO_LUGAR, LOD_NOMBRE, LOD_NOMBRE_CORTO, LOD_ESTADO, LOD_UBICACION_LATITUD, LOD_UBICACION_LONGITUD, PRO_ID)
SELECT 'PORTOVIEJO', 'Portoviejo', 'Portoviejo', 1, -1.0526, -80.454, PRO_ID FROM [ADMINISTRACION].[PROVINCIA] WHERE PRO_CODIGO = 'MAN'
UNION ALL
SELECT 'MONTAÑITA', 'Montañita', 'Montañita', 1, -2.7081, -80.8535, PRO_ID FROM [ADMINISTRACION].[PROVINCIA] WHERE PRO_CODIGO = 'MAN'
UNION ALL
SELECT 'ISLA_DE_LA_PLATA', 'Isla de la Plata', 'Plata', 1, -1.1855, -80.6044, PRO_ID FROM [ADMINISTRACION].[PROVINCIA] WHERE PRO_CODIGO = 'MAN';

-- Morona Santiago
INSERT INTO [ADMINISTRACION].[LUGAR] (LOD_CODIGO_LUGAR, LOD_NOMBRE, LOD_NOMBRE_CORTO, LOD_ESTADO, LOD_UBICACION_LATITUD, LOD_UBICACION_LONGITUD, PRO_ID)
SELECT 'MACAS', 'Macas', 'Macas', 1, -2.3006, -78.1204, PRO_ID FROM [ADMINISTRACION].[PROVINCIA] WHERE PRO_CODIGO = 'MSA'
UNION ALL
SELECT 'PARQUE_NACIONAL_YASUNI', 'Parque Nacional Yasuní', 'Yasuní', 1, -0.9745, -76.5479, PRO_ID FROM [ADMINISTRACION].[PROVINCIA] WHERE PRO_CODIGO = 'MSA'
UNION ALL
SELECT 'RÍO_MORONA', 'Río Morona', 'Morona', 1, -2.215, -78.0004, PRO_ID FROM [ADMINISTRACION].[PROVINCIA] WHERE PRO_CODIGO = 'MSA';

-- Napo
INSERT INTO [ADMINISTRACION].[LUGAR] (LOD_CODIGO_LUGAR, LOD_NOMBRE, LOD_NOMBRE_CORTO, LOD_ESTADO, LOD_UBICACION_LATITUD, LOD_UBICACION_LONGITUD, PRO_ID)
SELECT 'TENA', 'Tena', 'Tena', 1, -0.9884, -77.8197, PRO_ID FROM [ADMINISTRACION].[PROVINCIA] WHERE PRO_CODIGO = 'NAP'
UNION ALL
SELECT 'CASCADAS_DE_ANTONIO_SANTIAGO', 'Cascadas de Antonio Santiago', 'Antonio', 1, -0.7403, -77.6589, PRO_ID FROM [ADMINISTRACION].[PROVINCIA] WHERE PRO_CODIGO = 'NAP'
UNION ALL
SELECT 'PARQUE_NACIONAL_COTOCACHI', 'Parque Nacional Cotocachi', 'Cotocachi', 1, -0.5974, -77.8834, PRO_ID FROM [ADMINISTRACION].[PROVINCIA] WHERE PRO_CODIGO = 'NAP';

-- Pichincha
INSERT INTO [ADMINISTRACION].[LUGAR] (LOD_CODIGO_LUGAR, LOD_NOMBRE, LOD_NOMBRE_CORTO, LOD_ESTADO, LOD_UBICACION_LATITUD, LOD_UBICACION_LONGITUD, PRO_ID)
SELECT 'QUITO', 'Quito', 'Quito', 1, -0.1807, -78.4678, PRO_ID FROM [ADMINISTRACION].[PROVINCIA] WHERE PRO_CODIGO = 'PIC'
UNION ALL
SELECT 'COTOGCHO', 'Cotogcho', 'Cotogcho', 1, -0.3406, -78.4603, PRO_ID FROM [ADMINISTRACION].[PROVINCIA] WHERE PRO_CODIGO = 'PIC'
UNION ALL
SELECT 'LAGO_DE_SAN_PABLO', 'Lago de San Pablo', 'San Pablo', 1, -0.3474, -78.1415, PRO_ID FROM [ADMINISTRACION].[PROVINCIA] WHERE PRO_CODIGO = 'PIC';

-- Tungurahua
INSERT INTO [ADMINISTRACION].[LUGAR] (LOD_CODIGO_LUGAR, LOD_NOMBRE, LOD_NOMBRE_CORTO, LOD_ESTADO, LOD_UBICACION_LATITUD, LOD_UBICACION_LONGITUD, PRO_ID)
SELECT 'AMBATO', 'Ambato', 'Ambato', 1, -1.2445, -78.6187, PRO_ID FROM [ADMINISTRACION].[PROVINCIA] WHERE PRO_CODIGO = 'TUN'
UNION ALL
SELECT 'LAGUNA_DE_LOS_MOLINOS', 'Laguna de los Molinos', 'Molinos', 1, -1.2354, -78.6327, PRO_ID FROM [ADMINISTRACION].[PROVINCIA] WHERE PRO_CODIGO = 'TUN'
UNION ALL
SELECT 'PARQUE_NACIONAL_TUNGURAHUA', 'Parque Nacional Tungurahua', 'Tungurahua', 1, -1.2421, -78.6179, PRO_ID FROM [ADMINISTRACION].[PROVINCIA] WHERE PRO_CODIGO = 'TUN';

-- Santo Domingo de los Tsáchilas
INSERT INTO [ADMINISTRACION].[LUGAR] (LOD_CODIGO_LUGAR, LOD_NOMBRE, LOD_NOMBRE_CORTO, LOD_ESTADO, LOD_UBICACION_LATITUD, LOD_UBICACION_LONGITUD, PRO_ID)
SELECT 'SANTO_DOMINGO', 'Santo Domingo', 'Santo Domingo', 1, -0.2519, -79.1741, PRO_ID FROM [ADMINISTRACION].[PROVINCIA] WHERE PRO_CODIGO = 'SDT'
UNION ALL
SELECT 'LA_PAZ', 'La Paz', 'La Paz', 1, -0.2424, -79.1888, PRO_ID FROM [ADMINISTRACION].[PROVINCIA] WHERE PRO_CODIGO = 'SDT'
UNION ALL
SELECT 'LAGO_DE_SANTO_DOMINGO', 'Lago de Santo Domingo', 'Lago', 1, -0.2434, -79.1761, PRO_ID FROM [ADMINISTRACION].[PROVINCIA] WHERE PRO_CODIGO = 'SDT';

-- Zamora-Chinchipe
INSERT INTO [ADMINISTRACION].[LUGAR] (LOD_CODIGO_LUGAR, LOD_NOMBRE, LOD_NOMBRE_CORTO, LOD_ESTADO, LOD_UBICACION_LATITUD, LOD_UBICACION_LONGITUD, PRO_ID)
SELECT 'ZAMORA', 'Zamora', 'Zamora', 1, -4.0504, -78.9832, PRO_ID FROM [ADMINISTRACION].[PROVINCIA] WHERE PRO_CODIGO = 'ZCH'
UNION ALL
SELECT 'RÍO_YAMBE', 'Río Yambé', 'Yambé', 1, -4.0546, -79.0044, PRO_ID FROM [ADMINISTRACION].[PROVINCIA] WHERE PRO_CODIGO = 'ZCH'
UNION ALL
SELECT 'EL_VALLE', 'El Valle', 'Valle', 1, -4.0402, -78.9791, PRO_ID FROM [ADMINISTRACION].[PROVINCIA] WHERE PRO_CODIGO = 'ZCH';


INSERT INTO [ADMINISTRACION].[PUNTO_TRANSPORTE] ([PTT_CODIGO], [PTT_NOMBRE], [PTT_ESTADO], [PTT_TIPO], [PRO_ID], [PTT_UBICACION_LATITUD], [PTT_UBICACION_LONGITUD])
VALUES
('Quito-Quitumbe', 'Terminal Terrestre Quitumbe', 1, 1, (SELECT PRO_ID FROM [ADMINISTRACION].[PROVINCIA] WHERE PRO_NOMBRE = 'Pichincha'), -0.1807, -78.4678),
('Quito-Carcelén', 'Terminal Terrestre Carcelén', 1, 1, (SELECT PRO_ID FROM [ADMINISTRACION].[PROVINCIA] WHERE PRO_NOMBRE = 'Pichincha'), -0.1336, -78.5024),
('Quito-La Marín', 'Terminal La Marín', 1, 1, (SELECT PRO_ID FROM [ADMINISTRACION].[PROVINCIA] WHERE PRO_NOMBRE = 'Pichincha'), -0.1800, -78.4675),
('Quito-Ofelia', 'Terminal Ofelia', 1, 1, (SELECT PRO_ID FROM [ADMINISTRACION].[PROVINCIA] WHERE PRO_NOMBRE = 'Pichincha'), -0.1805, -78.4700),
('Quito-Río Coca', 'Terminal Río Coca', 1, 1, (SELECT PRO_ID FROM [ADMINISTRACION].[PROVINCIA] WHERE PRO_NOMBRE = 'Pichincha'), -0.1803, -78.4705),
('Guayaquil-Jaime Roldós', 'Terminal Terrestre Jaime Roldós Aguilera', 1, 1, (SELECT PRO_ID FROM [ADMINISTRACION].[PROVINCIA] WHERE PRO_NOMBRE = 'Guayas'), -2.1700, -79.9220),
('Guayaquil-Pascuales', 'Terminal Pascuales', 1, 1, (SELECT PRO_ID FROM [ADMINISTRACION].[PROVINCIA] WHERE PRO_NOMBRE = 'Guayas'), -2.2000, -79.9000),
('Cuenca', 'Terminal Terrestre de Cuenca', 1, 1, (SELECT PRO_ID FROM [ADMINISTRACION].[PROVINCIA] WHERE PRO_NOMBRE = 'Azuay'), -2.9000, -79.0048),
('Manta', 'Terminal Terrestre de Manta', 1, 1, (SELECT PRO_ID FROM [ADMINISTRACION].[PROVINCIA] WHERE PRO_NOMBRE = 'Manabí'), -0.9570, -80.7360),
('Portoviejo', 'Terminal Terrestre de Portoviejo', 1, 1, (SELECT PRO_ID FROM [ADMINISTRACION].[PROVINCIA] WHERE PRO_NOMBRE = 'Manabí'), -1.0520, -80.4540),
('Quevedo', 'Terminal Terrestre de Quevedo', 1, 1, (SELECT PRO_ID FROM [ADMINISTRACION].[PROVINCIA] WHERE PRO_NOMBRE = 'Los Ríos'), -1.0330, -79.4660),
('Riobamba', 'Terminal Terrestre de Riobamba', 1, 1, (SELECT PRO_ID FROM [ADMINISTRACION].[PROVINCIA] WHERE PRO_NOMBRE = 'Chimborazo'), -1.6660, -78.6540),
('Ambato', 'Terminal Terrestre de Ambato', 1, 1, (SELECT PRO_ID FROM [ADMINISTRACION].[PROVINCIA] WHERE PRO_NOMBRE = 'Tungurahua'), -1.2500, -78.6167),
('Loja', 'Terminal Terrestre de Loja', 1, 1, (SELECT PRO_ID FROM [ADMINISTRACION].[PROVINCIA] WHERE PRO_NOMBRE = 'Loja'), -4.0070, -79.2040),
('Ibarra', 'Terminal Terrestre de Ibarra', 1, 1, (SELECT PRO_ID FROM [ADMINISTRACION].[PROVINCIA] WHERE PRO_NOMBRE = 'Imbabura'), 0.3330, -78.9980),
('Tulcán', 'Terminal Terrestre de Tulcán', 1, 1, (SELECT PRO_ID FROM [ADMINISTRACION].[PROVINCIA] WHERE PRO_NOMBRE = 'Carchi'), 0.4500, -77.7167),
('Tena', 'Terminal Terrestre de Tena', 1, 1, (SELECT PRO_ID FROM [ADMINISTRACION].[PROVINCIA] WHERE PRO_NOMBRE = 'Napo'), -0.9830, -77.8080),
('Baños', 'Terminal Terrestre de Baños', 1, 1, (SELECT PRO_ID FROM [ADMINISTRACION].[PROVINCIA] WHERE PRO_NOMBRE = 'Tungurahua'), -1.4000, -78.4200),
('Atacames', 'Terminal Terrestre de Atacames', 1, 1, (SELECT PRO_ID FROM [ADMINISTRACION].[PROVINCIA] WHERE PRO_NOMBRE = 'Esmeraldas'), 0.9667, -79.0333);

GO
INSERT INTO [ADMINISTRACION].[COOPERATIVA]
	(
	[COP_CODIGO]
	,[COP_FECHA_REGISTRO]
	,[COP_FECHA_ULTIMA_ACTUALIZACION]
	,[COP_NOMBRE]
	,[COP_DESCRIPCION]
	,[COP_LOGO_IMAGEN_ID]
	,[COP_BUS_IMAGEN_ID]
	,[COP_ESTADO]
	)
VALUES
	(
		'TRANS_EXPRESS'
        , GETDATE()
        , GETDATE()
		, 'Coop. Transandina Express'
		, ''
		, NULL
		, NULL
		, 1
    ),
	(
		'IMBABURA'
        , GETDATE()
        , GETDATE()
		, 'Coop. Transportes Imbabura'
		, ''
		, NULL
		, NULL
		, 1
    ),
	(
		'PANAMERICANA'
        , GETDATE()
        , GETDATE()
		, 'Coop. Panamericana'
		, ''
		, NULL
		, NULL
		, 1
);
GO


IF NOT EXISTS (
    SELECT 1 FROM ADMINISTRACION.ARCHIVOS_GUARDADOS 
    WHERE ARG_NOMBRE = 'nombre_archivo' AND ARG_RUTA = 'ruta_archivo'
)
BEGIN
    INSERT INTO ADMINISTRACION.ARCHIVOS_GUARDADOS 
    (ARG_FECHA_REGISTRO, ARG_NOMBRE, ARG_RUTA, ARG_URL, ARG_ESTADO)
    VALUES (GETDATE(), 'nombre_archivo', 'ruta_archivo', NULL, 1);
END
GO
INSERT INTO ADMINISTRACION.SERVICIOS (
    SRV_FECHA_REGISTRO, 
    SRV_FECHA_ULTIMA_ACTUALIZACION, 
    SRV_CODIGO, 
    SRV_NOMBRE, 
    IMAGEN_ID
)
VALUES
    (GETDATE(), GETDATE(), 'ILUMINACION', 'Iluminación', (SELECT MIN(ARG_ID) FROM ADMINISTRACION.ARCHIVOS_GUARDADOS)),
    (GETDATE(), GETDATE(), 'AIRE', 'Aire Acondicionado', (SELECT MIN(ARG_ID) FROM ADMINISTRACION.ARCHIVOS_GUARDADOS)),
    (GETDATE(), GETDATE(), 'BAÑO', 'Baño', (SELECT MIN(ARG_ID) FROM ADMINISTRACION.ARCHIVOS_GUARDADOS));


INSERT INTO [ADMINISTRACION].[COOPERATIVA_BUS]
SELECT C.COP_ID,  CONCAT('BUS_'+C.COP_CODIGO,'_'), 1,1

FROM [ADMINISTRACION].[COOPERATIVA] C

INSERT INTO [ADMINISTRACION].[COOPERATIVA_BUS_SERVICIO]
SELECT CB.CPB_ID, S.SRV_ID, CONCAT(S.SRV_CODIGO,'_',cb.CPB_CODIGO), 1
FROM [ADMINISTRACION].[COOPERATIVA_BUS] CB
CROSS JOIN [ADMINISTRACION].[SERVICIOS] S

INSERT INTO [ADMINISTRACION].[PISO_DIAGRAMA_COOPERATIVA_BUS]
Select CPB_ID,  1,'PISO_1',''
 FROM [ADMINISTRACION].[COOPERATIVA_BUS]

INSERT INTO [ADMINISTRACION].[PISO_DIAGRAMA_COOPERATIVA_BUS]
Select CPB_ID,  2,'PISO_2',''
 FROM [ADMINISTRACION].[COOPERATIVA_BUS]

UPDATE[ADMINISTRACION].[PISO_DIAGRAMA_COOPERATIVA_BUS]
SET [PDB_DIAGRAMA] = '[ [ { "SeatIdentifier": "A1", "BusSpaceType": 0, "SeatState": 1 }, { "SeatIdentifier": "A2", "BusSpaceType": 0, "SeatState": 1 }, { "BusSpaceType": 1, }, { "SeatIdentifier": "A3", "BusSpaceType": 0, "SeatState": 1 }, { "SeatIdentifier": "A4", "BusSpaceType": 0, "SeatState": 1 } ], [ { "SeatIdentifier": "A5", "BusSpaceType": 0, "SeatState": 1 }, { "SeatIdentifier": "A6", "BusSpaceType": 0, "SeatState": 1 }, { "BusSpaceType": 1, }, { "SeatIdentifier": "A7", "BusSpaceType": 0, "SeatState": 1 }, { "SeatIdentifier": "A8", "BusSpaceType": 0, "SeatState": 1 } ], [ { "SeatIdentifier": "A9", "BusSpaceType": 0, "SeatState": 1 }, { "SeatIdentifier": "A10", "BusSpaceType": 0, "SeatState": 1 }, { "BusSpaceType": 1, }, { "SeatIdentifier": "A11", "BusSpaceType": 0, "SeatState": 1 }, { "SeatIdentifier": "A12", "BusSpaceType": 0, "SeatState": 1 } ], [ { "SeatIdentifier": "A13", "BusSpaceType": 0, "SeatState": 1 }, { "SeatIdentifier": "A14", "BusSpaceType": 0, "SeatState": 1 }, { "BusSpaceType": 1, }, { "SeatIdentifier": "A15", "BusSpaceType": 0, "SeatState": 1 }, { "SeatIdentifier": "A16", "BusSpaceType": 0, "SeatState": 1 } ], [ { "SeatIdentifier": "A17", "BusSpaceType": 0, "SeatState": 1 }, { "SeatIdentifier": "A18", "BusSpaceType": 0, "SeatState": 1 }, { "BusSpaceType": 1, }, { "SeatIdentifier": "A19", "BusSpaceType": 0, "SeatState": 1 }, { "SeatIdentifier": "A20", "BusSpaceType": 0, "SeatState": 1 } ], [ { "SeatIdentifier": "A21", "BusSpaceType": 0, "SeatState": 1 }, { "SeatIdentifier": "A22", "BusSpaceType": 0, "SeatState": 1 }, { "BusSpaceType": 1, }, { "SeatIdentifier": "A23", "BusSpaceType": 0, "SeatState": 1 }, { "SeatIdentifier": "A24", "BusSpaceType": 0, "SeatState": 1 } ], [ { "SeatIdentifier": "A25", "BusSpaceType": 0, "SeatState": 1 }, { "SeatIdentifier": "A26", "BusSpaceType": 0, "SeatState": 1 }, { "BusSpaceType": 1, }, { "SeatIdentifier": "A27", "BusSpaceType": 0, "SeatState": 1 }, { "SeatIdentifier": "A28", "BusSpaceType": 0, "SeatState": 1 } ], [ { "SeatIdentifier": "A29", "BusSpaceType": 0, "SeatState": 1 }, { "SeatIdentifier": "A30", "BusSpaceType": 0, "SeatState": 1 }, { "BusSpaceType": 1, }, { "SeatIdentifier": "A31", "BusSpaceType": 0, "SeatState": 1 }, { "SeatIdentifier": "A32", "BusSpaceType": 0, "SeatState": 1 } ], [ { "SeatIdentifier": "A33", "BusSpaceType": 0, "SeatState": 1 }, { "SeatIdentifier": "A34", "BusSpaceType": 0, "SeatState": 1 }, { "BusSpaceType": 1, }, { "SeatIdentifier": "A35", "BusSpaceType": 0, "SeatState": 1 }, { "SeatIdentifier": "A36", "BusSpaceType": 0, "SeatState": 1 } ], [ { "SeatIdentifier": "A37", "BusSpaceType": 0, "SeatState": 1 }, { "SeatIdentifier": "A38", "BusSpaceType": 0, "SeatState": 1 }, { "BusSpaceType": 1, }, { "SeatIdentifier": "A39", "BusSpaceType": 0, "SeatState": 1 }, { "SeatIdentifier": "A40", "BusSpaceType": 0, "SeatState": 1 } ], [ { "SeatIdentifier": "A41", "BusSpaceType": 0, "SeatState": 1 }, { "SeatIdentifier": "A42", "BusSpaceType": 0, "SeatState": 1 }, { "BusSpaceType": 1, }, { "SeatIdentifier": "A43", "BusSpaceType": 0, "SeatState": 1 }, { "SeatIdentifier": "A44", "BusSpaceType": 0, "SeatState": 1 } ], [ { "SeatIdentifier": "A45", "BusSpaceType": 0, "SeatState": 1 }, { "SeatIdentifier": "A46", "BusSpaceType": 0, "SeatState": 1 }, { "BusSpaceType": 1, }, { "SeatIdentifier": "A47", "BusSpaceType": 0, "SeatState": 1 }, { "SeatIdentifier": "A48", "BusSpaceType": 0, "SeatState": 1 } ], [ { "SeatIdentifier": "A49", "BusSpaceType": 0, "SeatState": 1 }, { "SeatIdentifier": "A50", "BusSpaceType": 0, "SeatState": 1 }, { "BusSpaceType": 1, }, { "SeatIdentifier": "A51", "BusSpaceType": 0, "SeatState": 1 }, { "SeatIdentifier": "A52", "BusSpaceType": 0, "SeatState": 1 } ], [ { "BusSpaceType": 1, }, { "BusSpaceType": 1, }, { "BusSpaceType": 1, }, { "BusSpaceType": 2, }, { "BusSpaceType": 2, } ], ]'


--Sirve para Verificar los puntos de salida o llegada que tiene cada compañia y el código correspondiente, esto permite verificar el origen entre provincias
INSERT INTO [ADMINISTRACION].[COOPERATIVA_PUNTO_TRANSPORTE]
SELECT PT.PTT_ID, C.COP_ID, PT.PTT_CODIGO FROM [ADMINISTRACION].[COOPERATIVA] C  CROSS JOIN [ADMINISTRACION].[PUNTO_TRANSPORTE] PT
