DECLARE @PAR_CODIGO VARCHAR(MAX) = 'MAX_COUNT_REFRESH_TOKEN'
DECLARE @PAR_NOMBRE VARCHAR(MAX) = 'Maximo contador de refresh token'
DECLARE @PAR_VALOR VARCHAR(MAX) = '5'
DECLARE @PAR_DESCRIPCION VARCHAR(MAX) = 'Maximo contador de refresh token' IF EXISTS (
        SELECT *
        FROM [ADMINISTRACION].[PARAMETRO]
        WHERE PAR_CODIGO = @PAR_CODIGO
    )
UPDATE [ADMINISTRACION].[PARAMETRO]
SET [PAR_CODIGO] = @PAR_CODIGO,
    [PAR_NOMBRE] = @PAR_NOMBRE,
    [PAR_VALOR] = @PAR_VALOR,
    [PAR_DESCRIPCION] = @PAR_DESCRIPCION,
    [PAR_ESTADO] = 1,
    [PAR_VERSION] = 1,
    [PAR_FECHA_REGISTRO] = GETDATE(),
    [PAR_FECHA_MOFICACION] = GETDATE(),
    [PAR_TIPO] = 1
WHERE PAR_CODIGO = @PAR_CODIGO
    ELSE
INSERT INTO [ADMINISTRACION].[PARAMETRO] (
        [PAR_CODIGO],
        [PAR_NOMBRE],
        [PAR_VALOR],
        [PAR_DESCRIPCION],
        [PAR_ESTADO],
        [PAR_VERSION],
        [PAR_FECHA_REGISTRO],
        [PAR_FECHA_MOFICACION],
        [PAR_TIPO]
    )
VALUES (
        @PAR_CODIGO,
        @PAR_NOMBRE,
        @PAR_VALOR,
        @PAR_DESCRIPCION,
        1,
        1,
        GETDATE(),
        GETDATE(),
        1
    )
SELECT *
FROM [ADMINISTRACION].[PARAMETRO]
WHERE PAR_CODIGO = @PAR_CODIGO
GO --
DECLARE @PAR_CODIGO VARCHAR(MAX) = 'MAX_ATTEMPTS_LOGIN_FAILED'
DECLARE @PAR_NOMBRE VARCHAR(MAX) = 'Máximo de intentos fallidos de logín para bloqueo'
DECLARE @PAR_VALOR VARCHAR(MAX) = '5'
DECLARE @PAR_DESCRIPCION VARCHAR(MAX) = 'Máximo de intentos fallidos de logín para bloqueo' IF EXISTS (
        SELECT *
        FROM [ADMINISTRACION].[PARAMETRO]
        WHERE PAR_CODIGO = @PAR_CODIGO
    )
UPDATE [ADMINISTRACION].[PARAMETRO]
SET [PAR_CODIGO] = @PAR_CODIGO,
    [PAR_NOMBRE] = @PAR_NOMBRE,
    [PAR_VALOR] = @PAR_VALOR,
    [PAR_DESCRIPCION] = @PAR_DESCRIPCION,
    [PAR_ESTADO] = 1,
    [PAR_VERSION] = 1,
    [PAR_FECHA_REGISTRO] = GETDATE(),
    [PAR_FECHA_MOFICACION] = GETDATE(),
    [PAR_TIPO] = 1
WHERE PAR_CODIGO = @PAR_CODIGO
    ELSE
INSERT INTO [ADMINISTRACION].[PARAMETRO] (
        [PAR_CODIGO],
        [PAR_NOMBRE],
        [PAR_VALOR],
        [PAR_DESCRIPCION],
        [PAR_ESTADO],
        [PAR_VERSION],
        [PAR_FECHA_REGISTRO],
        [PAR_FECHA_MOFICACION],
        [PAR_TIPO]
    )
VALUES (
        @PAR_CODIGO,
        @PAR_NOMBRE,
        @PAR_VALOR,
        @PAR_DESCRIPCION,
        1,
        1,
        GETDATE(),
        GETDATE(),
        1
    )
SELECT *
FROM [ADMINISTRACION].[PARAMETRO]
WHERE PAR_CODIGO = @PAR_CODIGO
GO --

DECLARE @PAR_CODIGO VARCHAR(MAX) = 'MAX_SECONDS_SEAT_RESERVED'
DECLARE @PAR_NOMBRE VARCHAR(MAX) = 'Máximo segundos de reserva asiento.'
DECLARE @PAR_VALOR VARCHAR(MAX) = '300'
DECLARE @PAR_DESCRIPCION VARCHAR(MAX) = 'Máximo de segundos para reservar un asiento' IF EXISTS (
        SELECT *
        FROM [ADMINISTRACION].[PARAMETRO]
        WHERE PAR_CODIGO = @PAR_CODIGO
    )
UPDATE [ADMINISTRACION].[PARAMETRO]
SET [PAR_CODIGO] = @PAR_CODIGO,
    [PAR_NOMBRE] = @PAR_NOMBRE,
    [PAR_VALOR] = @PAR_VALOR,
    [PAR_DESCRIPCION] = @PAR_DESCRIPCION,
    [PAR_ESTADO] = 1,
    [PAR_VERSION] = 1,
    [PAR_FECHA_REGISTRO] = GETDATE(),
    [PAR_FECHA_MOFICACION] = GETDATE(),
    [PAR_TIPO] = 1
WHERE PAR_CODIGO = @PAR_CODIGO
    ELSE
INSERT INTO [ADMINISTRACION].[PARAMETRO] (
        [PAR_CODIGO],
        [PAR_NOMBRE],
        [PAR_VALOR],
        [PAR_DESCRIPCION],
        [PAR_ESTADO],
        [PAR_VERSION],
        [PAR_FECHA_REGISTRO],
        [PAR_FECHA_MOFICACION],
        [PAR_TIPO]
    )
VALUES (
        @PAR_CODIGO,
        @PAR_NOMBRE,
        @PAR_VALOR,
        @PAR_DESCRIPCION,
        1,
        1,
        GETDATE(),
        GETDATE(),
        1
    )
SELECT *
FROM [ADMINISTRACION].[PARAMETRO]
WHERE PAR_CODIGO = @PAR_CODIGO
GO

DECLARE @PAR_CODIGO VARCHAR(MAX) = 'MAX_SECONDS_ORDER_RESERVED'
DECLARE @PAR_NOMBRE VARCHAR(MAX) = 'Máximo segundos de reserva orden.'
DECLARE @PAR_VALOR VARCHAR(MAX) = '300'
DECLARE @PAR_DESCRIPCION VARCHAR(MAX) = 'Máximo de segundos para reservar una Orden' IF EXISTS (
        SELECT *
        FROM [ADMINISTRACION].[PARAMETRO]
        WHERE PAR_CODIGO = @PAR_CODIGO
    )
UPDATE [ADMINISTRACION].[PARAMETRO]
SET [PAR_CODIGO] = @PAR_CODIGO,
    [PAR_NOMBRE] = @PAR_NOMBRE,
    [PAR_VALOR] = @PAR_VALOR,
    [PAR_DESCRIPCION] = @PAR_DESCRIPCION,
    [PAR_ESTADO] = 1,
    [PAR_VERSION] = 1,
    [PAR_FECHA_REGISTRO] = GETDATE(),
    [PAR_FECHA_MOFICACION] = GETDATE(),
    [PAR_TIPO] = 1
WHERE PAR_CODIGO = @PAR_CODIGO
    ELSE
INSERT INTO [ADMINISTRACION].[PARAMETRO] (
        [PAR_CODIGO],
        [PAR_NOMBRE],
        [PAR_VALOR],
        [PAR_DESCRIPCION],
        [PAR_ESTADO],
        [PAR_VERSION],
        [PAR_FECHA_REGISTRO],
        [PAR_FECHA_MOFICACION],
        [PAR_TIPO]
    )
VALUES (
        @PAR_CODIGO,
        @PAR_NOMBRE,
        @PAR_VALOR,
        @PAR_DESCRIPCION,
        1,
        1,
        GETDATE(),
        GETDATE(),
        1
    )
SELECT *
FROM [ADMINISTRACION].[PARAMETRO]
WHERE PAR_CODIGO = @PAR_CODIGO
GO

DECLARE @PAR_CODIGO VARCHAR(MAX) = 'MAX_SEAT_RESERVED_DEFAULT'
DECLARE @PAR_NOMBRE VARCHAR(MAX) = 'Máximo número de asientos permitidos para reservar'
DECLARE @PAR_VALOR VARCHAR(MAX) = '5'
DECLARE @PAR_DESCRIPCION VARCHAR(MAX) = 'Máximo número de asientos permitidos para reservar' IF EXISTS (
        SELECT *
        FROM [ADMINISTRACION].[PARAMETRO]
        WHERE PAR_CODIGO = @PAR_CODIGO
    )
UPDATE [ADMINISTRACION].[PARAMETRO]
SET [PAR_CODIGO] = @PAR_CODIGO,
    [PAR_NOMBRE] = @PAR_NOMBRE,
    [PAR_VALOR] = @PAR_VALOR,
    [PAR_DESCRIPCION] = @PAR_DESCRIPCION,
    [PAR_ESTADO] = 1,
    [PAR_VERSION] = 1,
    [PAR_FECHA_REGISTRO] = GETDATE(),
    [PAR_FECHA_MOFICACION] = GETDATE(),
    [PAR_TIPO] = 1
WHERE PAR_CODIGO = @PAR_CODIGO
    ELSE
INSERT INTO [ADMINISTRACION].[PARAMETRO] (
        [PAR_CODIGO],
        [PAR_NOMBRE],
        [PAR_VALOR],
        [PAR_DESCRIPCION],
        [PAR_ESTADO],
        [PAR_VERSION],
        [PAR_FECHA_REGISTRO],
        [PAR_FECHA_MOFICACION],
        [PAR_TIPO]
    )
VALUES (
        @PAR_CODIGO,
        @PAR_NOMBRE,
        @PAR_VALOR,
        @PAR_DESCRIPCION,
        1,
        1,
        GETDATE(),
        GETDATE(),
        1
    )
SELECT *
FROM [ADMINISTRACION].[PARAMETRO]
WHERE PAR_CODIGO = @PAR_CODIGO
GO

