CREATE TABLE [ADMINISTRACION].[CATALOGO] (
    [CAT_ID]     INT           IDENTITY (1, 1) NOT NULL,
    [CAT_CODIGO] VARCHAR (64)  NOT NULL,
    [CAT_NOMBRE] VARCHAR (64)  NOT NULL,
    [CAT_PADRE]  INT           NULL,
    [CAT_ESTADO] BIT           NOT NULL,
    [CAT_VALOR]  VARCHAR (128) NULL
);
GO

CREATE UNIQUE NONCLUSTERED INDEX [UQ_CODIGO]
    ON [ADMINISTRACION].[CATALOGO]([CAT_CODIGO] ASC);
GO

ALTER TABLE [ADMINISTRACION].[CATALOGO]
    ADD CONSTRAINT [FK_CATALOGO_CATALOGO] FOREIGN KEY ([CAT_PADRE]) REFERENCES [ADMINISTRACION].[CATALOGO] ([CAT_ID]);
GO

ALTER TABLE [ADMINISTRACION].[CATALOGO]
    ADD CONSTRAINT [PK_CATALOGO] PRIMARY KEY CLUSTERED ([CAT_ID] ASC);
GO

